### ISSUE TITLE
bug: 画质解锁失败，旧版新版播放器都不行，在上一版本里这个功能大部分时间是正常的

### ISSUE THREAD

**Issue by jiaozhudezhuzhu** [BiliRoamingX/BiliRoamingX#143]
### 系统版本

索尼原生

### Android 版本

12

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

version 7.70.0

### 问题描述

打开4k或者类似会员分辨率无效，要求加入会员，之前版本正常

### 复现步骤

每次都是这样

### 日志

没root

**Comment by zjns** [comment]
这个功能标注为实验性的，视频能否试看取决于接口下发数据是否有播放地址，能试看会有试看的标签，只有会员的标签说明这个视频接口没有下发会员画质的播放地址。
