### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Honggea** [BiliRoamingX/BiliRoamingX#146]
### 系统版本

one ui

### Android 版本

13

### 哔哩哔哩版本

HD 版

### 哔哩哔哩版本号

1.46

### 问题描述

开发者你好，最新版HD版设置底部功能隐藏和显示没有反应，请求更新一下，处理一下这个bug问题。非常感谢

### 复现步骤

1.打开
2.进入设置
3.进入漫游X
4.首页
5.需要展示的底栏
6.勾选了只显示动态、我的
7.重启
8.首页面还是有。

### 日志

XX

**Comment by zjns** [comment]
HD 版不支持。
