### ISSUE TITLE
无法分享至lspatch的play版微信

### ISSUE THREAD

**Issue by Choultion-Rudas** [BiliRoamingX/BiliRoamingX#147]
### 系统版本

EMUI 11

### Android 版本

10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76.0

### 问题描述

使用净化分享，无法分享至lspatch的play版微信，但可以分享至lspatch的QQ，并且评论区无法点击图片显示大图

### 复现步骤

1. 点击分享至微信，显示请先安装微信，然后显示分享失败
2. 点击评论区图片，没有反应，不能查看大图

### 日志

[log.txt](https://github.com/BiliRoamingX/BiliRoamingX/files/15093731/log.txt)

**Comment by zjns** [comment]
1. 那就只能分享到QQ
2. 无法复现

**Comment by zjns** [comment]
第二点解决办法 https://github.com/BiliRoamingX/BiliRoamingX/issues/148#issuecomment-2074912701
