### ISSUE TITLE
bug: 评论区图片无法打开，且长按无法保存

### ISSUE THREAD

**Issue by guli457** [BiliRoamingX/BiliRoamingX#148]
### 系统版本

澎湃os

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76.0

### 问题描述

评论区图片无法打开，且长按无法保存

### 复现步骤

1.打开视频【小老师露出坚毅的眼神，但是小登的琴诺已经开始笑了-哔哩哔哩】 https://b23.tv/rz0Ov2J
2.点击评论区图片无法放大，且长按无法下载

### 日志

[log.txt](https://github.com/BiliRoamingX/BiliRoamingX/files/15094368/log.txt)

### 截图或录屏

https://github.com/BiliRoamingX/BiliRoamingX/assets/96912568/e2696cef-69cf-4bf9-b64e-a5643afbd4b7

### 补充信息

【小老师露出坚毅的眼神，但是小登的琴诺已经开始笑了-哔哩哔哩】 https://b23.tv/rz0Ov2J

**Comment by zjns** [comment]
有时间的话备份下装个官方7.76版本看看有没有问题

**Comment by Lyen233** [comment]
我使用旧版播放器也这样，切换到新版解决
