### ISSUE TITLE
动态页的【关注】标签或【视频】标签下的视频点进去100%闪退，查看图文专栏的文字或图片则不会闪退

### ISSUE THREAD

**Issue by razilong** [BiliRoamingX/BiliRoamingX#149]
### 系统版本

MIUI14

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76

### 问题描述

锁定播放器为旧版时，  动态页的【关注】标签或【视频】标签等标签下的视频(无论横版、竖版)点进去100%闪退。查看图文专栏的文字或图片则不会闪退。

锁定为新版播放器则无闪退， 虽然可能是官方bug，您是否有意愿将其修复? 因为旧版播放器真的很好用😭

### 复现步骤

  。

### 日志

[log.txt](https://github.com/BiliRoamingX/BiliRoamingX/files/15095422/log.txt)
[tombstones.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15095425/tombstones.zip)

**Comment by zjns** [comment]
旧版播放器下动态页下所有的视频点击都会闪退？我看好像闪退的好像都是合集？

**Comment by zjns** [comment]
不管了，就当解决了
