### ISSUE TITLE
bug: 启动闪退

### ISSUE THREAD

**Issue by lgernierO** [BiliRoamingX/BiliRoamingX#150]
### 系统版本

Color OS12.1

### Android 版本

12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76.0

### 问题描述

APP启动时闪退

### 复现步骤

启动时会闪退，一般闪退一次再启动就能进来，有时候闪退好几次才能进来

### 日志

[tombstones.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15095993/tombstones.zip)
[log.txt](https://github.com/BiliRoamingX/BiliRoamingX/files/15095989/log.txt)

**Comment by zjns** [comment]
不应该呀，这个问题我处理过了，还是有，怪了

**Comment by zjns** [comment]
@lgernierO @liumingye 用这个[修复包](https://github.com/BiliRoamingX/BiliRoamingX-PreBuilds/releases/latest)试试看

**Comment by lgernierO** [comment]
我的没问题了

**Comment by lgernierO** [comment]
> @lgernierO @liumingye用这个[修复包](https://github.com/BiliRoamingX/BiliRoamingX-PreBuilds/releases/latest)试看

我的没问题了

**Comment by liumingye** [comment]
> @lgernierO @liumingye 用这个[修复包](https://github.com/BiliRoamingX/BiliRoamingX-PreBuilds/releases/latest)试试看

能进去了
