### ISSUE TITLE
评论区图片无法点击

### ISSUE THREAD

**Issue by Lights47** [BiliRoamingX/BiliRoamingX#151]
### 系统版本

MIUI 14

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76.0

### 问题描述

最新版评论区图片无法点击

### 复现步骤

随便打开了个视频，发现评论区图片无法点击放大

### 日志

[log.txt](https://github.com/BiliRoamingX/BiliRoamingX/files/15097525/log.txt)

**Comment by zjns** [comment]
官方bug，使用新版播放器
