### ISSUE TITLE
bug:最新版本1.20.1更新后评论图片无法点开

### ISSUE THREAD

**Issue by CelestialEclispe** [BiliRoamingX/BiliRoamingX#152]
### 系统版本

HarmonyOS 4.2.0.137

### Android 版本

12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76.0

### 问题描述

更新推送的最新版本整合包后视频评论区的图片无法点开大图

### 复现步骤

1.打开视频评论区
2.找到带图评论
3.点击无法打开

### 日志

暂无

### 截图或录屏

https://github.com/BiliRoamingX/BiliRoamingX/assets/36039688/acadbb75-bc35-45ef-b912-a1adbacff884

**Comment by Lyen233** [comment]
把播放器切换到新版试试？

**Comment by Lyen233** [comment]
我使用旧版播放器也存在这个问题，新版播放器则正常

**Comment by Lyen233** [comment]
> 我使用旧版播放器也存在这个问题，新版播放器则正常

试了下，新版播放器正常似乎是因为7.76.0已经官方支持评论区图片保存
