### ISSUE TITLE
7.76.0版本的旧版播放器的评论区笔记图片无法点开

### ISSUE THREAD

**Issue by LingQizs** [BiliRoamingX/BiliRoamingX#156]
### 系统版本

澎湃OS1.0

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76.0

### 问题描述

旧版播放器评论区笔记图片无法点开

### 复现步骤

1.设置播放器为旧版
2.打开视频评论区
3.点击评论区笔记中的图片
4.无任何反应，没有打开操作

### 日志

暂无

### 补充信息

似乎是原版b站同版本下已经实现评论区笔记直接保存至相册，但不知道为什么限制了旧版播放器。现在7.76.0版本评论区笔记图片无法点开，之前的7.70.0版本下旧版播放器可以点开。
开发者可以看看有什么解决方法吗？

**Comment by zjns** [comment]
也许官方后续版本会修复
