### ISSUE TITLE
bug:新版本动态页面的视频打开闪退（点开up的主页打开的视频正常）

### ISSUE THREAD

**Issue by kaayuri** [BiliRoamingX/BiliRoamingX#158]
### 系统版本

MIUI14.0.2

### Android 版本

12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76.0

### 问题描述

在动态页面点开视频会闪退，首页视频正常

### 复现步骤

1.点击打开动态页面的视频
2.闪退

### 日志

[log.txt](https://github.com/BiliRoamingX/BiliRoamingX/files/15104620/log.txt)

### 截图或录屏

Uploading 动态视频闪退.mp4…

### 解决办法

未知

### 补充信息

无

**Comment by zjns** [comment]
漫游 X 杂项打开允许三方 APP 访问私有存储，mt 管理器添加本地存储，把 data/files/tombstones 文件夹打包贴在这

**Comment by kaayuri** [comment]
我没有在/storage/emulated/0/Android/data/tv.danmaku.bili/files/看见tombstones文件夹，抱歉我不太懂

**Comment by zjns** [comment]
https://github.com/BiliRoamingX/BiliRoamingX/issues/137#issuecomment-2041490147 @kaayuri

**Comment by kaayuri** [comment]
[tombstones.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15105543/tombstones.zip)
找到了

**Comment by zjns** [comment]
用的旧版播放器？哪个视频会有这个问题？

**Comment by kaayuri** [comment]
试了下，是旧版播放器的问题，旧版播放器动态里的视频打开就会闪退，up转发的视频不会

**Comment by zjns** [comment]
能给个有问题的视频 bvid 不，我这边并不能复现

**Comment by kaayuri** [comment]
跟视频无关，是用旧版播放器打开动态的任意视频都会闪退（点到up主页中打开视频没事）
图中这种转发的不会
![QQ图片20240425174133](https://github.com/BiliRoamingX/BiliRoamingX/assets/95112913/e06f845a-9c6e-4ade-8390-22c06df41007)

**Comment by zjns** [comment]
那不管了，代码或者接口返回的数据有问题，我虽然可以解决，但没必要，感觉是官方的 bug，官方要想解决只需要修一下接口就行了，都不用发版。

**Comment by kaayuri** [comment]
好的，麻烦你了 ：）

**Comment by zjns** [comment]
又看了下，可能是强制旧版播放器某个地方没处理好，能不能再开启调试模式用旧版播放器试下打开动态的的视频，然后日志把 log.txt 和 old_log.txt 都贴上来

**Comment by kaayuri** [comment]
[log.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15108668/log.zip)
