### ISSUE TITLE
bug: 笔记图片长按预览保存，失效，无法点击图片查看，无法预览保存

### ISSUE THREAD

**Issue by thutwrac** [BiliRoamingX/BiliRoamingX#160]
### 系统版本

miui14

### Android 版本

android11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

哔哩哔哩粉版 7.76.0(7760700) with 漫游X 1.20.1

### 问题描述

bug: 笔记图片长按预览保存，失效，无法点击图片查看，无法预览保存

### 复现步骤

bug: 笔记图片长按预览保存，失效，无法点击图片查看，无法预览保存

### 日志

![Screenshot_20240425_192419](https://github.com/BiliRoamingX/BiliRoamingX/assets/20200782/3c7a7ceb-6633-4864-95d5-365caa324adf)

### 截图或录屏

![Screenshot_20240425_192419](https://github.com/BiliRoamingX/BiliRoamingX/assets/20200782/a4f58262-6fec-4b2d-b8df-f439dee7cb51)

### 补充信息

测试，我测试了有图片的评论，均出现了问题，这个问题之前旧版本没有。

**Comment by Liow7** [comment]
我的也是，虽然b站添加了这个功能，但是我把备份的设置导入到软件就会出现和你一样的情况，点不开图片。如果单独打开新软件(漫游x的设置为出厂)就可以点开。希望大大能看一下这是啥情况。
