### ISSUE TITLE
feat: 限制横向视频只能横向全屏

### ISSUE THREAD

**Issue by nothingshiru** [BiliRoamingX/BiliRoamingX#163]
### 原因

我的vivo平板更新OriginOS 4(Android 14)后，竖屏打开全屏还是竖屏，想要横向全屏不得不关闭方向锁，很不方便
![Screenshot_20240426_135500](https://github.com/BiliRoamingX/BiliRoamingX/assets/79258245/4dd44d11-babd-4215-8f04-c5a87b301d6b)

### 功能简述

限制横向视频的全屏方向只能是横屏

### 功能逻辑

在哔哩漫游X的播放器设置新增一个开关选项

**Comment by zjns** [comment]
系统问题就别来找我了
