### ISSUE TITLE
隐藏评论区「充电评论」评论图标

### ISSUE THREAD

**Issue by WangYi640** [BiliRoamingX/BiliRoamingX#164]
### 原因

更新新版播放器后，评论区显示「充电评论」的图标，挤占评论文本的位置。

![Screenshot_20240426_180854](https://github.com/BiliRoamingX/BiliRoamingX/assets/132351967/b9b83739-ee27-492f-a39e-43f2113e4d51)
![Screenshot_20240426_180934](https://github.com/BiliRoamingX/BiliRoamingX/assets/132351967/13b3858b-54ad-442d-974a-b21dadc2c5f6)

### 功能简述

屏蔽充电评论图标的选项
或只显示充电图标而不显示充电评论四个字

### 功能逻辑

在设置里面增加选项
＊望作者大大考虑一下(◦˙▽˙◦)

**Comment by zjns** [comment]
这也太细了吧，有能力PR，我不想搞
