### ISSUE TITLE
评论区氛围屏蔽功能

### ISSUE THREAD

**Issue by Ehoumaki** [BiliRoamingX/BiliRoamingX#165]
### 原因

希望增加评论氛围评价屏蔽功能，总是出现看着好烦

### 功能简述

增加功能按钮屏蔽
![Screenshot_2024-04-27-15-22-01-621_tv danmaku bili](https://github.com/BiliRoamingX/BiliRoamingX/assets/54829009/65f6709c-76fc-4bb2-b392-229c0bd73528)

### 功能逻辑

增加功能按钮屏蔽

**Comment by zjns** [comment]
也没有总是出现吧，不容易抓到，不搞
