### ISSUE TITLE
bug: 评论区图片无法点击放大

### ISSUE THREAD

**Issue by 0721master** [BiliRoamingX/BiliRoamingX#166]
### 系统版本

miui14

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

1.20.1

### 问题描述

评论区图片无法点击放大

### 复现步骤

打开评论区，看见别人发的图片，尝试点击进入查看但无反应，因此也无法保存图片

### 日志

[log_哔哩哔哩.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15137873/log_.zip)

**Comment by Lyen233** [comment]
![Screenshot_2024-04-27-18-41-29-894_com.github.android-edit.jpg](https://github.com/BiliRoamingX/BiliRoamingX/assets/165792082/cbb06c8f-1468-456f-bbda-702583512eea)
