### ISSUE TITLE
feat: 粉版功能重复

### ISSUE THREAD

**Issue by shalen233** [BiliRoamingX/BiliRoamingX#167]
### 原因

7.76版本中，官方已经提供了关闭首页刷新和评论区保存图片的功能(Play版本最新的3.19.0仅更新了关闭首页自动刷新)
![483db9ccdf4ffbb3d9fcdda3b3aeadd5](https://github.com/BiliRoamingX/BiliRoamingX/assets/100697404/b75c59f1-ead2-4934-966d-4365611b5d0e)
![eef29ea0e54793e97672895cc70a1876_720](https://github.com/BiliRoamingX/BiliRoamingX/assets/100697404/00f13012-337c-42dc-8cd4-d0ae9e3a0de5)

### 功能简述

在最新版中将这一类功能取消调整

### 功能逻辑

类似之前的“禁止自动跳转到动态”选项
![454c2d56a54fe0a6786acee65e447c06](https://github.com/BiliRoamingX/BiliRoamingX/assets/100697404/5ab35d38-78bf-4aef-af0d-328d1f166f0d)

**Comment by zjns** [comment]
禁止首页自动刷新这个，虽然官方有了，但是默认是关闭的吧，那模块禁用了这个功能，原本用的好好的，突然又自动刷新了，那不怪到我头上来了

**Comment by shalen233** [comment]
确实，B站官方也从来不好好写更新日志，我也是给别人设置时才发现的()

**Comment by zjns** [comment]
不过可以在禁用模块功能时开启官方的功能，只是稍微麻烦点
