### ISSUE TITLE
屏蔽番剧页面大会员广告

### ISSUE THREAD

**Issue by WangYi640** [BiliRoamingX/BiliRoamingX#169]
### 原因

在新版播放器中，播放会出现大会员广告
![Screenshot_20240427_232834](https://github.com/BiliRoamingX/BiliRoamingX/assets/132351967/4dbea193-e4ce-4cee-8c64-ea6ae74f7797)

### 功能简述

增加屏蔽贴片选项

### 功能逻辑

像屏蔽up主推荐广告那样
![IMG_20240427_234421](https://github.com/BiliRoamingX/BiliRoamingX/assets/132351967/3bed4b91-b22f-4f6d-8631-be74e828d9d8)

**Comment by zjns** [comment]
2ee5bffef202f0410979fff97c335213a14da4d5
