### ISSUE TITLE
添加设置项搜索功能

### ISSUE THREAD

**Issue by WangYi640** [BiliRoamingX/BiliRoamingX#170]
### 原因

随着设置项目越来越多，很难快速找到设置项

### 功能简述

添加设置搜索内容功能（尤其是漫游x的功能）

### 功能逻辑

例如:在右上角放个搜索图标

### 实现参考

QAuxiliary

![IMG_20240427_235003](https://github.com/BiliRoamingX/BiliRoamingX/assets/132351967/64208367-514f-43ab-aa16-9849241cc5ce)
![Screenshot_20240427_235050](https://github.com/BiliRoamingX/BiliRoamingX/assets/132351967/af53785d-11ac-40fa-97bb-a4600cdee838)

一点小小的建议₍˄·͈༝·͈˄*₎◞ ̑̑

**Comment by zjns** [comment]
麻烦，设置项分类已经做的比较清晰了，先挂着吧

**Comment by Aira-Sakuranomiya** [comment]
刚开始用的表示确实挺难找的，要慢慢找（
