### ISSUE TITLE
增量更新包导致的签名错误

### ISSUE THREAD

**Issue by JinHaoliag** [BiliRoamingX/BiliRoamingX#172]
### 系统版本

Harmony OS 4

### Android 版本

UNKNOWN

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76.0

### 复现步骤

1.打开7.76.0版本的Bilibili
2.检查更新
3.增量更新
4.安装包签名错误

### 日志

无

### 截图或录屏

![Screenshot_20240428_213154_tv danmaku bili](https://github.com/BiliRoamingX/BiliRoamingX/assets/87127521/d6fc9f85-0025-4295-b7cd-42c7351f4e76)
![Screenshot_20240428_212817_com android packageinstaller](https://github.com/BiliRoamingX/BiliRoamingX/assets/87127521/876d95de-a4ef-4ef2-adf8-bca5e70d7fec)

**Comment by zjns** [comment]
你在想什么？改的包用的是又不是哔哩哔哩官方的签名，当然不能直接更新官方的包。

**Comment by JinHaoliag** [comment]
> 你在想什么？改的包用的签名不是哔哩哔哩官方的签名，当然不能直接更新官方的包。

抱歉我看成了是修改后的更新
