### ISSUE TITLE
feat: 禁用直播间P2P上传

### ISSUE THREAD

**Issue by msm8976** [BiliRoamingX/BiliRoamingX#174]
### 原因

在WiFi环境下观看直播时，会通过P2P上传占用带宽

### 功能简述

自定义禁用直播间P2P上传功能

### 功能逻辑

设置-直播间中新增一个选项，打开后禁用直播间P2P上传功能

### 实现参考

哔哩漫游：https://github.com/yujincheng08/BiliRoaming/blob/master/app/src/main/java/me/iacn/biliroaming/hook/P2pHook.kt
根据官方APP逻辑流量状态下不会启用P2P上传，也可修改直播间获取到的网络环境

**Comment by zjns** [comment]
对于这种行为我是支持的

**Comment by Zhuxiuan** [comment]
能不能多加一个视频的呢

**Comment by msm8976** [comment]
@Zhuxiuan 我直接改包把P2P删了 https://t.me/msm8976_apks/47

**Comment by Zhuxiuan** [comment]
> @Zhuxiuan我直接改包把P2P删除了https://t.me/msm8976_apks/47
嗯，可以了，非常谢谢

**Comment by msm8976** [comment]
记录一下，若后续有更新计划可加入
去除直播P2P上传：com.bilibili.bililive.source.LivePlayerItem类相关方法 或ff_live_room_player_close_p2p设置为true
去除主站P2P：tv.danmaku.ijk.media.player.P2P parseConfig方法返回null

**Comment by zjns** [comment]
貌似这个 P2P 会导致运营商认为你在滥用流量做 PCDN，从而限速，有必要处理下了
