### ISSUE TITLE
feat: 请求软件内集成包更新留有可直达下载更新包位置的选项

### ISSUE THREAD

**Issue by ArcS17** [BiliRoamingX/BiliRoamingX#175]
### 原因

HarmonyOS设备软件内集成包更新被识别为恶意安装源, 无法更新。但从文件管理器手动安装apk文件可以正常更新
![Screenshot_20240429_160040](https://github.com/BiliRoamingX/BiliRoamingX/assets/94548426/f8c40eb1-9be1-4ea8-9a1b-699c6cb67b19)
![Screenshot_20240429_161129_com huawei appmarket](https://github.com/BiliRoamingX/BiliRoamingX/assets/94548426/7d23907e-e54f-44ed-a928-35d3220fe6a7)

### 功能简述

请求软件内集成包更新留有可直达下载集成更新包的文件位置的button或文档中补充软件内集成包更新下载位置

### 功能逻辑

绕过华为令人恶心的安装源检测, 手动安装软件内集成包更新所下载的apk文件

**Comment by zjns** [comment]
https://github.com/BiliRoamingX/BiliRoamingX?tab=readme-ov-file#%EF%B8%8F-%E4%B8%8B%E8%BD%BD%E4%BD%BF%E7%94%A8
