### ISSUE TITLE
能否支持 NPatch共存版 取得 App 原始签名

### ISSUE THREAD

**Issue by HSSkyBoy** [BiliRoamingX/BiliRoamingX#176]
### 原因

因为平常不太使用NPatch原版(LSPatch)而是使用NPatch共存版，所以我无论是打包QQ还是打包微信都无法取得哔哩哔哩的原始签名
在我分析了lspatch获取的原理之后，我觉得npatch也可以，于是修改了一下apk的xml，于是成功了
![Screenshot_20240430_222435_com huawei android launcher_edit_183188253853296](https://github.com/BiliRoamingX/BiliRoamingX/assets/122550437/ebc425aa-14b1-4a20-8773-24770a2eb4d5)
虽然我也不知道为什么共存版显示是426...

修改后的文件我放在了实现参考

### 功能简述

NPatch共存版 可取得 App 原始签名

### 功能逻辑

APK→https://t.me/bbx_show/23
XML→[AndroidManifest.xml改.txt](https://github.com/BiliRoamingX/BiliRoamingX/files/15166331/AndroidManifest.xml.txt)

### 实现参考

已经实现该功能的应用↑
我不太会写，但根据原理我写了一下，看看可不可以，还没测试https://github.com/HSSkyBoy/BiliRoamingX/commit/9b23a2c4214c646a3afa82930b31eb960518e75a
如果可以的话通知我，我来PR，万分感谢 :P

**Comment by zjns** [comment]
这个键值应该可以跟 lspatch 的完全一样吧，我来处理吧

**Comment by HSSkyBoy** [comment]
> 这个键值应该可以跟 lspatch 的完全一样吧，我来处理吧

加油(｡•̀ᴗ-)✧
