### ISSUE TITLE
关于新版播放器的会员画质功能的部分问题

### ISSUE THREAD

**Issue by 3049298988** [BiliRoamingX/BiliRoamingX#177]
### 系统版本

HyperOS

### Android 版本

13/14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76.0

### 问题描述

联通/电信流量状态下新版播放器无法使用会员画质
移动不清楚

切换回WIFI并重进视频即可正常使用

手机开热点可以正常使用（只测了电信卡开热点）

也就是说，这玩意检测是否使用流量

### 复现步骤

使用流量
打开会员画质功能
设置播放器版本为新版
打开随便一个视频

### 日志

[log.txt](https://github.com/BiliRoamingX/BiliRoamingX/files/15173254/log.txt)
不清楚log是否有用

**Comment by 3049298988** [comment]
使用模块伪装网络类型为 WIFI 后
可以正常使用新版播放器画质破解

**Comment by zjns** [comment]
还有这个操作？应该可以解决

**Comment by 3049298988** [comment]
> 也就是说，这玩意检测是否使用流量

使用模块伪装网络类型为 WIFI 后
可以正常使用新版播放器画质破解

**Comment by 3049298988** [comment]
> 还有这个操作？应该可以解决

解决的话会和免流冲突，有点麻烦，新版播放器疑似有些太抽象了

**Comment by zjns** [comment]
> > 还有这个操作？应该可以解决
> 
> 解决的话会和免流冲突，有点麻烦，新版播放器疑似有些太抽象了

接口请求数据可能加了网络类型，改了就行

**Comment by 3049298988** [comment]
> > > 还有这个操作？应该可以解决
> > 
> > 
> > 解决的话会和免流冲突，有点麻烦，新版播放器疑似有些太抽象了
> 
> 接口请求数据可能加了网络类型，改了就行

好好好！
