### ISSUE TITLE
状态栏通知图标修复

### ISSUE THREAD

**Issue by vitanonoka** [BiliRoamingX/BiliRoamingX#179]
### 系统版本

Android 14

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.70.0

### 问题描述

![Screenshot_20240501-153223_Via~2](https://github.com/BiliRoamingX/BiliRoamingX/assets/135424710/7c46e9ee-fd4e-4b67-a870-612f3d5d4487)
![Screenshot_20240501-153636_相册](https://github.com/BiliRoamingX/BiliRoamingX/assets/135424710/ee64aeb6-c8e2-412a-afac-eb3d543016b3)
原生安卓下通知形状为一个圆，请求修复

### 复现步骤

原生下通知图标显示为圆

### 日志

xxx

**Comment by zjns** [comment]
官方的问题，我不想动手
