### ISSUE TITLE
bug: 新版播放器只能解锁番剧会员画质

### ISSUE THREAD

**Issue by cczliangg** [BiliRoamingX/BiliRoamingX#180]
### 系统版本

HyperOS

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76.0

### 问题描述

在大佬的提醒切换新版播放器，刚开始的时候新版播放器还可以解锁会员画质，到后来只有番剧可以解锁会员画质，up自制的全部解锁不了！（数据和WiFi都试过了）

### 复现步骤

无

### 日志

[log_哔哩哔哩.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15180768/log_.zip)

### 截图或录屏

无

**Comment by zjns** [comment]
不能就说明阿B不想让你试看了
