### ISSUE TITLE
bug: 画质功能失效

### ISSUE THREAD

**Issue by Zhuxiuan** [BiliRoamingX/BiliRoamingX#181]
### 系统版本

MIUI13

### Android 版本

12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.75

### 问题描述

在用户空间使用播放全部视频功能时无限试用画质会失效，用7.42粉版的播放全部视频功能就没有这个问题

### 复现步骤

1.打开某个up用户空间2.播放全部视频

### 日志

[log_哔哩哔哩.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15188000/log_.zip)

### 截图或录屏

![Screenshot_2024-05-02-20-02-21-389_tv danmaku bili](https://github.com/BiliRoamingX/BiliRoamingX/assets/147717282/3031b237-bd42-4998-a190-cec5c9b49e9e)
![Screenshot_2024-05-02-20-02-14-107_tv danmaku bili](https://github.com/BiliRoamingX/BiliRoamingX/assets/147717282/7c081930-6c26-4369-8ee0-9af9e8d586ed)
![Screenshot_2024-05-02-19-57-25-871_tv danmaku bili](https://github.com/BiliRoamingX/BiliRoamingX/assets/147717282/3a9d31f2-4172-406a-9819-e4da591fbda1)

### 解决办法

使用旧版播放全部

**Comment by zjns** [comment]
上传日志的时候叫你打开调试模式复现一遍，你没看见？
