### ISSUE TITLE
bug: 用流量看视频无法试用会员画质

### ISSUE THREAD

**Issue by 727w7w8w** [BiliRoamingX/BiliRoamingX#183]
### 系统版本

MIUI14

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76.0

### 问题描述

用流量看视频无法试用会员画质

### 复现步骤

无

### 日志

无

### 截图或录屏

![Screenshot_2024-05-03-06-48-44-350_tv danmaku bili](https://github.com/BiliRoamingX/BiliRoamingX/assets/105539917/22e5381c-c246-47a9-94f5-d948aed40157)

### 解决办法

用流量看视频无法试用会员画质

**Comment by zjns** [comment]
已经修了

**Comment by 727w7w8w** [comment]
> 已经修了

没有😢
