### ISSUE TITLE
打包问题（之前的issues看不到了）

### ISSUE THREAD

**Issue by axiuluoshiwo** [BiliRoamingX/BiliRoamingX#184]
### 系统版本

originos4

### Android 版本

14

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

3.19.0

### 问题描述

利用termux打包，3.18.2可以成功，3.19.0打不开，会闪退

### 复现步骤

正常打包，3.18.2可以正常运行，19.0就不行

### 日志

问题就是上面的

**Comment by zjns** [comment]
actions最新的ci构建打包
