### ISSUE TITLE
希望添加“批量取关功能”

### ISSUE THREAD

**Issue by M-HLSLY** [BiliRoamingX/BiliRoamingX#189]
### 原因

今天用着发现关注已满（上限3000人），手动取关太麻烦

### 功能简述

希望能批量取关up（如果能设定条件，比如多久未更新，是否有标之类的）

### 功能逻辑

镶嵌在“关注页面”，取关前可以弹个窗口提示将要取关up名字二次确认

### 实现参考

抱歉，不会:(

**Comment by zjns** [comment]
找一找有没有网页脚本或插件，APP就不搞了，麻烦，不值当
