### ISSUE TITLE
竖屏视频新版播放器简介可自由复制

### ISSUE THREAD

**Issue by HSSkyBoy** [BiliRoamingX/BiliRoamingX#190]
### 原因

自由复制功能目前无法在新版竖屏播放器的简洁界面复制
如图
![Screenshot_20240505_113010_tv danmaku bili](https://github.com/BiliRoamingX/BiliRoamingX/assets/122550437/268a5893-3afd-4209-bfca-d9ae6c16998e)

### 功能简述

可在竖屏新版播放器的简介页面复制

### 功能逻辑

自由复制

**Comment by zjns** [comment]
原本就不能长按复制
