### ISSUE TITLE
详情页切换至竖屏滑动视频，再切换至详情页，自由复制中的简介不对应

### ISSUE THREAD

**Issue by HSSkyBoy** [BiliRoamingX/BiliRoamingX#191]
### 系统版本

鸿蒙4.0.0.118

### Android 版本

12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76.0

### 问题描述

从主页点开一个视频，并且切换到竖屏模式，滑动到其他视频的时候再切换至详情页打开简介，而自由复制并不是当前视频内容，而是原先点开的视频内容

### 复现步骤

1.开启自由复制
2.主页点开任意视频(详情页)
3.切换到竖屏模式
4.往下滑动至任意视频(5+)
5.切换至详情页
6.长按复制简介

### 日志

[log_哔哩漫游X.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15211753/log_.zip)

### 截图或录屏

https://github.com/BiliRoamingX/BiliRoamingX/assets/122550437/138d9487-2453-4645-b9a4-b5f49c1472d2

(视频是H256格式，可能需要下载播放)

**Comment by zjns** [comment]
实现问题，可能不好解决

**Comment by zjns** [comment]
并不能复现

**Comment by HSSkyBoy** [comment]
> 并不能复现

大佬，你不能往下多划几个吗？最新CI构建仍然有这个问题
