### ISSUE TITLE
bug: 自由复制文本不默认铺满全屏

### ISSUE THREAD

**Issue by WangYi640** [BiliRoamingX/BiliRoamingX#192]
### 系统版本

origin os 2

### Android 版本

11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76

### 问题描述

自由复制评论时显示文本自动折叠一部分（大概一行） 需要滑动一下才能显示下半部分
长评和短评都有这个问题

### 复现步骤

1.进入任意一个视频（用的旧版播放器）
2.打开评论区
3.长按复制

### 日志

-

### 截图或录屏

https://github.com/BiliRoamingX/BiliRoamingX/assets/132351967/2d995390-c568-46f9-8f3d-7e27e6c0f690

**Comment by zjns** [comment]
视频简介复制是不是也有问题

**Comment by WangYi640** [comment]
> 视频简介复制是不是也有问题

简介复制是正常的

![Screenshot_20240505_133907](https://github.com/BiliRoamingX/BiliRoamingX/assets/132351967/524114b8-a28d-43d2-93b5-1f66665accf8)
![Screenshot_20240505_133935](https://github.com/BiliRoamingX/BiliRoamingX/assets/132351967/f8fe8327-8604-4f66-ac2e-a9afda7c7e56)

**Comment by zjns** [comment]
那就不修了

**Comment by WangYi640** [comment]
> 只有旧版播放器评论区中的评论有问题，长笔记是没有问题的，希望作者快快修复 (所以怎么还有人用旧播放器)

因为新版新版播放器是网页，而旧的播放器是原生的。用起来性能会更好（捂脸）

**Comment by zjns** [comment]
> > 只有旧版播放器评论区中的评论有问题，长笔记是没有问题的，希望作者快快修复 (所以怎么还有人用旧播放器)
> 
> 因为新版播放器是网页，而旧的播放器是原生的。用起来性能会更好（捂脸）

哪个跟你说是网页，这么核心的页面怎么可能可能用web，性能更好也是你yy出来的吧

**Comment by WangYi640** [comment]
> > > 只有旧版播放器评论区中的评论有问题，长笔记是没有问题的，希望作者快快修复 (所以怎么还有人用旧播放器)
> > 
> > 因为新版播放器是网页，而旧的播放器是原生的。用起来性能会更好（捂脸）
> 
> 哪个跟你说是网页，这么核心的页面怎么可能可能用web，性能更好也是你yy出来的吧

我看视频详情界面没有边界布局，抱歉，是我说错了~>_<~

**Comment by HSSkyBoy** [comment]
> 那就不修了

所以真就没修啊，怪不得新CI还有这个问题，还好旧播放器没啥人用，也不用修了，不劳烦你了
