### ISSUE TITLE
哔哩HD上滑为小窗时黑屏 bug: HD版本的不论是上滑为小窗还是自动转屏为竖屏都会黑屏，100%复现，不论机型

### ISSUE THREAD

**Issue by shixiaoqiangla** [BiliRoamingX/BiliRoamingX#194]
### 系统版本

Flyme10.5 鸿蒙4.2

### Android 版本

13

### 哔哩哔哩版本

HD 版

### 哔哩哔哩版本号

1.46.0 (release-b14270523)

### 问题描述

将APP滑动为小窗就会黑屏，自动旋转成为竖屏显示后再返回上一界面也是黑屏

### 复现步骤

将APP滑动为小窗就会黑屏，自动旋转成为竖屏显示后再返回上一界面也是黑屏

### 日志

[log_哔哩哔哩HD.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15212805/log_.HD.zip)

### 截图或录屏

![S40505-19545516_tv danmaku bilibilihd](https://github.com/BiliRoamingX/BiliRoamingX/assets/97492032/f5d10bad-8ca6-47d9-b6f1-42b1e640a562)

### 解决办法

无

### 补充信息

无

**Comment by zjns** [comment]
这难道不是官方的bug吗？

**Comment by shixiaoqiangla** [comment]
不是，我刚刚试了，官方没有这个问题


来自 MEIZU 21

-------- 原始邮件 --------
发件人：Kofua ***@***.***>
时间：2024年5月5日 19:58
收件人：BiliRoamingX/BiliRoamingX ***@***.***>
抄送：shixiaoqiangla ***@***.***>,Author ***@***.***>
主题：Re: [BiliRoamingX/BiliRoamingX] 哔哩HD上滑为小窗时黑屏 bug: HD版本的不论是上滑为小窗还是自动转屏为竖屏都会黑屏，100%复现，不论机型 (Issue #194)
