### ISSUE TITLE
bug: 频道中心部分功能失效

### ISSUE THREAD

**Issue by NaNaChiSama** [BiliRoamingX/BiliRoamingX#198]
### 系统版本

ColorOS 14

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.77.0

### 问题描述

用漫游添加出来的频道中心“我的收藏”栏加载不出来，我记得之前是能加载出来的，我没办法排除是哔哩哔哩有动作还是漫游的问题，就只能先抓个日志反馈bug了

### 复现步骤

1.打开哔哩哔哩
2.切换到“我的”页
3.点击“频道中心”

### 日志

[log_哔哩哔哩.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15214309/log_.zip)

### 截图或录屏

![Screenshot_2024-05-06-03-50-14-38_149003a2d400f6adb210d7e357a3a646](https://github.com/BiliRoamingX/BiliRoamingX/assets/97809275/ffeba8cf-c571-456c-8a1f-de3bfc295f02)

**Comment by zjns** [comment]
官方问题
