### ISSUE TITLE
feat: 建议

### ISSUE THREAD

**Issue by do02fw** [BiliRoamingX/BiliRoamingX#203]
### 原因

没有问题，建议修改搭建方法，这样更适合小白，人人都可以无脑编译，建议作者修改一下 https://github.com/BiliRoamingX/BiliRoamingX?tab=readme-ov-file#%EF%B8%8F-%E4%B8%8B%E8%BD%BD%E4%BD%BF%E7%94%A8 的步骤，这个不太适合小白，我这个方法适合小白无脑编译

### 功能简述

我分享一下自己的编译方法，测试过OK的

### 功能逻辑

首先，准备一个服务器，系统Ubuntu22.04，配置起码4核8G内存，建议去腾讯云或者阿里云开个按量计费，用完就销毁。
服务器执行命令安装jdk 
sudo apt install openjdk-21-jdk -y

执行命令下载所需要的文件
wget https://github.com/zjns/revanced-cli/releases/download/v4.6.0.1/revanced-cli.jar && wget https://github.com/BiliRoamingX/BiliRoamingX/releases/download/v1.20.3/BiliRoamingX-integrations-1.20.3.apk && wget https://github.com/BiliRoamingX/BiliRoamingX/releases/download/v1.20.3/BiliRoamingX-patches-1.20.3.jar && wget https://dl.hdslb.com/mobile/latest/android64/iBiliPlayer-bili.apk

编译
java -jar revanced-cli.jar patch --merge BiliRoamingX-integrations-1.20.3.apk --patch-bundle BiliRoamingX-patches-1.20.3.jar --signing-levels 2,3 iBiliPlayer-bili.apk

成功后会输出iBiliPlayer-bili-patched.apk

**Comment by do02fw** [comment]
Windows其实也可以，但是只能openjdk，不然会出问题

**Comment by zjns** [comment]
手机termux都可以，用啥服务器

**Comment by do02fw** [comment]
> 手机termux都可以，用啥服务器

为什么不做一个一键编译的脚本，反正很简单
