### ISSUE TITLE
bug: 首页推荐突然出现轮播广告

### ISSUE THREAD

**Issue by mlminge** [BiliRoamingX/BiliRoamingX#205]
### 系统版本

realme ui4.0

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

v7.77.0

### 问题描述

首页推荐突然出现轮播广告，今晚出现的

### 复现步骤

打开应用就有，刷新还有，晚上突然出现的，之前正常

### 日志

[log_哔哩哔哩.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15235212/log_.zip)

### 截图或录屏

![Screenshot_2024-05-07-20-04-44-74_149003a2d400f6adb210d7e357a3a646](https://github.com/BiliRoamingX/BiliRoamingX/assets/169157702/2e1089a2-6cf4-4423-9641-36fb930e8ffb)
![Screenshot_2024-05-07-19-57-26-81_149003a2d400f6adb210d7e357a3a646](https://github.com/BiliRoamingX/BiliRoamingX/assets/169157702/570f234c-53d2-47db-8f01-9dcc5b7ada76)

**Comment by zjns** [comment]
广告有广告标签
