### ISSUE TITLE
关于已失效的视频

### ISSUE THREAD

**Issue by bentang6** [BiliRoamingX/BiliRoamingX#206]
### 原因

对于失效的视频感到可惜，但可以通过小手段来获取已失效视频之前的封面

### 功能简述

能够让失效的视频显示出失效之前的视频封面

### 功能逻辑

让失效的视频显示出之前的封面

**Comment by zjns** [comment]
不懂什么小手段，指明下呢

**Comment by WangYi640** [comment]
> 不懂什么小手段，指明下呢

1.新建一个空的收藏夹
2.将失效的视频移动到刚建好的收藏夹（仅网页端可操作）
3.使用app端将该收藏夹分享到动态
4.可在动态相关界面查看到该收藏夹的封面（也就是失效视频的那个封面）~
