### ISSUE TITLE
收藏夹不见了

### ISSUE THREAD

**Issue by liangchencop** [BiliRoamingX/BiliRoamingX#208]
### 系统版本

。

### Android 版本

。

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

1.20.3

### 问题描述

收藏夹不见了

### 复现步骤

打开头像那里的主页，然后收藏夹没了

### 日志

。

### 截图或录屏

。

**Comment by HSSkyBoy** [comment]
什么消息都不说，截图也不给，自己去设置看看是不是自己屏蔽了？提的什么狗屁问题
