### ISSUE TITLE
屏蔽首页[课堂]标签类视频

### ISSUE THREAD

**Issue by Yukino002** [BiliRoamingX/BiliRoamingX#209]
### 原因

https://m.bilibili.com/cheese/play/ss1460
![Screenshot_2024-05-08-06-47-09-00_149003a2d400f6adb210d7e357a3a646](https://github.com/BiliRoamingX/BiliRoamingX/assets/145914152/cebf3a0f-a180-44cd-9a0a-602711d652c0)

### 功能简述

屏蔽

### 功能逻辑

不想在首页刷到这种视频

### 实现参考

感谢就这样

**Comment by zjns** [comment]
按类型过滤

**Comment by Yukino002** [comment]
![Screenshot_2024-05-08-19-42-36-67_149003a2d400f6adb210d7e357a3a646.jpg](https://github.com/BiliRoamingX/BiliRoamingX/assets/145914152/508cafd2-42de-406d-b8dd-881de5c47e75)

抱歉，其实我已经打开了这些(我不是很明白内联视频是指什么类型，互动视频？)

**Comment by zjns** [comment]
> ![Screenshot_2024-05-08-19-42-36-67_149003a2d400f6adb210d7e357a3a646.jpg](https://private-user-images.githubusercontent.com/145914152/328876280-508cafd2-42de-406d-b8dd-881de5c47e75.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjk1MTQsIm5iZiI6MTcxNTE2OTIxNCwicGF0aCI6Ii8xNDU5MTQxNTIvMzI4ODc2MjgwLTUwOGNhZmQyLTQyZGUtNDA2ZC1iOGRkLTg4MWRlNWM0N2U3NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQxMTUzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzE3NzJjMWQwMzQ2NmQ2NjAwZjE0MGMwMDM2Y2ExMWIwMTE0YTRhODZiZWI0MTg2NzYzZTI0Y2VlNThkOWViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DKzDu82LPK_NAf-GqjfG95_wUlaUYsODpSIn4V4HzQg)
> 
> 抱歉，其实我已经打开了这些(我不是很明白内联视频是指什么类型，互动视频？)

看错了，确实没有课程这一类，你可以开启调试模式，遇到了把日志上传到这

**Comment by HSSkyBoy** [comment]
所以是不是忘了把它重新打开...@zjns

**Comment by Yukino002** [comment]
> > 抱歉，其实我已经打开了这些(我不是很明白内联视频是指什么类型，互动视频？)
> 
> 看错了，确实没有课程这一类，你可以开启调试模式，遇到了把日志上传到这

你好我已经将在首页遇到[课堂]标签类型视频的日志发送往kofua邮箱大小约为5.8MB。
