### ISSUE TITLE
哥们，真的很抱歉，那个反馈我认真重写了一份

### ISSUE THREAD

**Issue by liangchencop** [BiliRoamingX/BiliRoamingX#218]
### 系统版本

OPPO ren 10

### Android 版本

coloros 14.0

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

1.20.3

### 问题描述

主页收藏夹位置没了(上个版本还在的)

### 复现步骤

打开左上角头像的主页，然后下方的收藏夹没了

### 日志

[log_哔哩哔哩.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15251665/log_.zip)

### 截图或录屏

![IMG_20240508_235750](https://github.com/BiliRoamingX/BiliRoamingX/assets/142915271/aa5559e8-9fb7-4340-9bc6-323dcd6e6f5f)
![IMG_20240509_000322](https://github.com/BiliRoamingX/BiliRoamingX/assets/142915271/db2f09b4-a5a9-47a0-8804-3ae4b41cf9d2)

### 补充信息

哥们真的很抱歉，昨晚的梯子快过期，就发的很匆忙，那个问题也是昨天发现的，我自己觉得这个问题比较明显，大佬能比较快的发现，所以填的很草率。真的很抱歉浪费大佬的空余时间，现在认真填写了，希望大佬能够处理一下

**Comment by WangYi640** [comment]
漫游设置-我的页-需要展示的项目
把收藏重新勾上就行了
