### ISSUE TITLE
bug: 华为平板发现恶意安装来源，无法安装

### ISSUE THREAD

**Issue by zpoyqx** [BiliRoamingX/BiliRoamingX#219]
### 系统版本

鸿蒙4.0

### Android 版本

12

### 哔哩哔哩版本

HD 版

### 哔哩哔哩版本号

1.46.0

### 问题描述

从APP界面弹窗自动安装Bili漫游时，最后安装会出现下面的警告信息，导致无法安装

### 复现步骤

![Screenshot_20240509_102851_tv danmaku bilibilihd](https://github.com/BiliRoamingX/BiliRoamingX/assets/56358596/40d2d5b8-3718-453e-a8f7-fda76908486f)
![Screenshot_20240508_152736_com huawei appmarket](https://github.com/BiliRoamingX/BiliRoamingX/assets/56358596/76eb965e-ac14-44d5-9374-09f9fc8f3579)

### 日志

非运行问题，如有需要再上传

**Comment by HSSkyBoy** [comment]
那就自己去 Release 下载，不要从APP里更新安装包或者去[TG集成包频道](t.me/bbx_show)下载
我是鸿蒙4.0.0.118这和漫游差没关系
