### ISSUE TITLE
倍速問題

### ISSUE THREAD

**Issue by NeKoOuO** [BiliRoamingX/BiliRoamingX#220]
### 系统版本

MIUI14

### Android 版本

13

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

1.20.3

### 问题描述

加速無法改變

### 复现步骤

正常點進去觀看，（默認倍速是1.25）想要調速度，但是直接點1無法改變，要先點1.25或0.75等其他的倍速選項才有辦法改變速度

### 日志

[log.txt](https://github.com/BiliRoamingX/BiliRoamingX/files/15259724/log.txt)

**Comment by HSSkyBoy** [comment]
长按视频变倍速之后就能恢复正常

**Comment by zjns** [comment]
这么多功能我又不是全部在用，又没人提，那就是没问题了

**Comment by HSSkyBoy** [comment]
> 这么多功能我又不是全部在用，又没人提，那就是没问题了

我是patched1.6开始用的，不知道哪个版本出现的问题，没想到现在才有人提出来这个问题，我一直以为是特性(⑉• •⑉) 以后是只要感觉有问题就都来反馈呗，您不觉得麻烦和打扰吧？

**Comment by zjns** [comment]
> > 这么多功能我又不是全部在用，又没人提，那就是没问题了
> 
> 我是patched1.6开始用的，不知道哪个版本出现的问题，没想到现在才有人提出来这个问题，我一直以为是特性(⑉• •⑉) 以后是只要感觉有问题就都来反馈呗，您不觉得麻烦和打扰吧？

尽管提，但不一定修
