### ISSUE TITLE
Support Deeplink 

### ISSUE THREAD

**Issue by NeKoOuO** [BiliRoamingX/BiliRoamingX#222]
### 原因

每次都要開瀏覽器跳轉太麻煩了

### 功能简述

點擊連結能直接跳轉

### 功能逻辑

要設置一個能設定是否開啟連結的入口

### 实现参考

YouTube Revanced extended 
![IMG_20240510_035131.jpg](https://github.com/BiliRoamingX/BiliRoamingX/assets/111511925/9a718b83-ccd5-4988-b4dd-6e4c21298af5)
![Screenshot_2024-05-10-03-49-17-341_com.android.settings.jpg](https://github.com/BiliRoamingX/BiliRoamingX/assets/111511925/18a2db80-3a02-451f-9048-40ecc724f1f0)

**Comment by 1852178459** [comment]
![Screenshot_20240510_070058.jpg](https://github.com/BiliRoamingX/BiliRoamingX/assets/111245751/e07da304-338c-4785-9f84-645358999c76)

这不是有吗

**Comment by NeKoOuO** [comment]
🤔 你哪裡開的我怎麼找不到入口
