### ISSUE TITLE
feat: 可不可以精简哔哩哔哩安装包，直接在代码中删除广告

### ISSUE THREAD

**Issue by do02fw** [BiliRoamingX/BiliRoamingX#227]
### 原因

可不可以精简哔哩哔哩安装包，直接在代码中删除广告，这样更流畅，另外删除多余的权限和服务

### 功能简述

可以自己编译精简哔哩哔哩安装包，直接在代码中删除广告，这样更流畅，另外删除多余的权限和服务

### 功能逻辑

比如增加一个选项，可以在编译时精简哔哩哔哩安装包，直接在代码中删除广告，删除多余的权限和服务

### 实现参考

比如一些国外APP的MOD版

**Comment by zjns** [comment]
搞清楚 revanced 原理再来提问

**Comment by do02fw** [comment]
我只会无脑编译
