### ISSUE TITLE
强烈建议增加功能：哔哩发评反诈

### ISSUE THREAD

**Issue by do02fw** [BiliRoamingX/BiliRoamingX#228]
### 原因

发出去的评论一刷新就没了

### 功能简述

可以在发送评论的时候检测评论是否被屏蔽

### 功能逻辑

发送评论时如果检测到评论被阻止将提示是否继续发送。

### 实现参考

https://modules.lsposed.org/module/icu.freedomintrovert.bilisendcommantifraud/

**Comment by zjns** [comment]
准守哔哩哔哩评论规则

**Comment by do02fw** [comment]
即使遵守了也容易误封

**Comment by WangYi640** [comment]
b站的阿瓦隆系统会自动删评
1.评论触发关键词
2.当前视频为敏感视频（尤其是政治敏感，或曾出现过大量辱骂评论）几乎禁止所有账号评论
3.当前账号在多个敏感视频发表过评论，会被阿瓦隆标记，提高限制门槛（有的词有的账号能发，有的账号不能发）

建议发评论之前 自行判断视频和评论内容是否为敏感内容 提前将内容复制到剪切板
如果发长评，建议都复制一下，因为难免会某些地方触发关键词
