### ISSUE TITLE
恢复点👎的按钮

### ISSUE THREAD

**Issue by do02fw** [BiliRoamingX/BiliRoamingX#230]
### 原因

有的视频，比如央视频发的一些视频只有点赞的按钮，没有点踩的按钮

### 功能简述

恢复所有视频都可以点踩

### 功能逻辑

恢复点踩的按钮

**Comment by WangYi640** [comment]
我还没有遇到过，很好奇，能发个bv号吗（ '▿ ' ）

**Comment by do02fw** [comment]
> 我还没有遇到过，很好奇，能发个bv号吗（ '▿ ' ）

https://www.bilibili.com/video/BV19m421u7cA @zjns

**Comment by WangYi640** [comment]
> > 我还没有遇到过，很好奇，能发个bv号吗（ '▿ ' ）
> 
> https://www.bilibili.com/video/BV19m421u7cA @zjns 

B站点踩按键的主要作用是
点踩人数过多，会打回重新审核（例如引战视频）
这种视频只有特定账号能发 而且b站也不敢给打回
如果不想看到，可以屏蔽标题，拉黑up
不建议冲塔，想表达观点可去外网平台

**Comment by WangYi640** [comment]
> > > 我还没有遇到过，很好奇，能发个bv号吗（ '▿ ' ）
> > 
> > https://www.bilibili.com/video/BV19m421u7cA @zjns 
> 
> B站点踩按键的主要作用是
> 点踩人数过多，会打回重新审核（例如引战视频）
> 这种视频只有特定账号能发 而且b站也不敢给打回
> 如果不想看到，可以屏蔽标题，拉黑up
> 不建议冲塔
