### ISSUE TITLE
閃退

### ISSUE THREAD

**Issue by NeKoOuO** [BiliRoamingX/BiliRoamingX#232]
### 系统版本

MIUI14

### Android 版本

13

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

1.20.3

### 问题描述

留言時閃退

### 复现步骤

打開留言區打字，拖動位置時閃退

### 日志

[log.txt](https://github.com/BiliRoamingX/BiliRoamingX/files/15286615/log.txt)

**Comment by zjns** [comment]
通过漫游 X 关于里的的分享日志按钮分享日志

**Comment by NeKoOuO** [comment]
![log_bilibili.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15287002/log_bilibili.zip)

**Comment by zjns** [comment]
用了什么奇怪的 xposed 或者 magisk 插件了吧，全都是剪贴板相关 API 引起的，跟模块没有关系，上次也是这个问题

**Comment by NeKoOuO** [comment]
可能是嗶哩嗶哩反詐
