### ISSUE TITLE
bug: 关于底包7.77.0旋转锁定的相关问题

### ISSUE THREAD

**Issue by 3049298988** [BiliRoamingX/BiliRoamingX#235]
### 系统版本

HyperOS

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.77.0

### 问题描述

关闭旋转锁定后，无法通过上滑进入多任务清理界面/很快滑动才能回到桌面

### 复现步骤

打开任意横屏视频并全屏
关闭旋转锁定
上滑进入多任务清理界面

### 日志

log为空（0b）

### 解决办法

更新底包/给官方擦屁股，重写旋转逻辑

**Comment by 3049298988** [comment]
这是演示视频：


https://github.com/BiliRoamingX/BiliRoamingX/assets/61861526/9d300db3-7602-4e17-8b50-f74b8bcba5d0

**Comment by zjns** [comment]
HyperOS特色

**Comment by 3049298988** [comment]
> HyperOS特色

已解决，鉴定为手机管家自动任务识别问题
改为延迟触发即可
![Screenshot_20240520-024048](https://github.com/BiliRoamingX/BiliRoamingX/assets/61861526/73835e87-5ef3-403c-896f-3061a36c9655)
![Screenshot_20240520-024103](https://github.com/BiliRoamingX/BiliRoamingX/assets/61861526/bac3d588-198e-4c4c-9d16-344720ade47c)
