### ISSUE TITLE
bug: 收藏选项不见了

### ISSUE THREAD

**Issue by hekroxx** [BiliRoamingX/BiliRoamingX#236]
### 系统版本

miui14

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.77.0

### 问题描述

![Screenshot_2024-05-14-16-39-22-133_tv danmaku bili-edit](https://github.com/BiliRoamingX/BiliRoamingX/assets/169768757/b4a2156c-8197-4ca0-b71f-e0368e55d814)

### 复现步骤

我的页面收藏选项不见了

### 日志

[BiliRoamingX_backup_20240514164807.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15305784/BiliRoamingX_backup_20240514164807.zip)

### 截图或录屏

![Screenshot_2024-05-14-16-39-22-133_tv danmaku bili-edit](https://github.com/BiliRoamingX/BiliRoamingX/assets/169768757/f8adde24-d118-4d60-a2f1-9619e52653db)

**Comment by HSSkyBoy** [comment]
https://github.com/BiliRoamingX/BiliRoamingX/issues/218
已有重复漏洞提交，请自行检查设置
