### ISSUE TITLE
feat: 新的广告

### ISSUE THREAD

**Issue by susuWA** [BiliRoamingX/BiliRoamingX#240]
### 原因

新广告太阴间了，大的一批
![Screenshot_2024-05-15-16-46-58-731_tv danmaku bili](https://github.com/BiliRoamingX/BiliRoamingX/assets/125103193/3ea38452-da11-4be1-afc6-1e46cf189b1b)

### 功能简述

屏蔽广告🙏🏻🙏🏻🙏🏻

### 功能逻辑

屏蔽

### 实现参考

移除视频浮窗

**Comment by zjns** [comment]
请补充视频BV号
