### ISSUE TITLE
bug: 已root的手机直接安装不会在lsp里显示模块,无法启用到官方版本中,只能用集成版本了...

### ISSUE THREAD

**Issue by supersnsd** [BiliRoamingX/BiliRoamingX#241]
### 系统版本

coloros13.1

### Android 版本

安卓13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.77-7.78

### 问题描述

已root的手机直接安装不会在lsp里显示模块,无法启用到官方版本中,只能用集成版本了...
还是希望启用电报群直接反馈,另外也希望增加支持云视听小电视(bilitv版本)

### 复现步骤

暂无

### 日志

无

**Comment by zjns** [comment]
本来就不是xposed模块
