### ISSUE TITLE
feat: 可以考虑调用画中画实现小窗吗

### ISSUE THREAD

**Issue by AkiraOrigin** [BiliRoamingX/BiliRoamingX#242]
### 原因

![Screenshot_20240516-044848](https://github.com/BiliRoamingX/BiliRoamingX/assets/29331017/f0222068-8aae-4ea7-9577-f2d0ca331a52)
![Screenshot_20240516-044919](https://github.com/BiliRoamingX/BiliRoamingX/assets/29331017/b644e595-05e6-4403-8768-890c461f1f21)
画中画是有适配系统圆角的

### 功能简述

调用安卓原生的画中画

### 功能逻辑

设置里添加画中画替换原来显示在其它应用上层的选项，打开之后点击视频界面的小窗播放变成PiP

### 实现参考

YouTube Netflix Disney

**Comment by zjns** [comment]
不是一句话的事情，给官方提建议
