### ISSUE TITLE
搜索页bug

### ISSUE THREAD

**Issue by TangBaoY** [BiliRoamingX/BiliRoamingX#244]
### 系统版本

coloros 7.1

### Android 版本

10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.78.0

### 问题描述

未开净化搜索页功能 但热搜不见了

### 复现步骤

![Screenshot_2024-05-16-10-07-44-32_149003a2d400f6adb210d7e357a3a646](https://github.com/BiliRoamingX/BiliRoamingX/assets/113247009/00c024d3-60af-4683-83f0-d147139e8832)
![IMG_20240516_100833](https://github.com/BiliRoamingX/BiliRoamingX/assets/113247009/b8b72457-16fd-4635-bc90-2b8c47c87a05)

### 日志

无

**Comment by SCmenghua** [comment]
同款bug，开关净化都没用

**Comment by wanguiy** [comment]
把净化开屏推广关闭就可以了
