### ISSUE TITLE
bug: 搜索页的净化搜索页面开关处于关闭状态，但还是去除了热搜和推荐

### ISSUE THREAD

**Issue by 3182785169** [BiliRoamingX/BiliRoamingX#248]
### 系统版本

ColorOS 12.1

### Android 版本

12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.78.0

### 问题描述

搜索页的净化搜索页面开关处于关闭状态，但还是去除了热搜和推荐

### 复现步骤

1.打开搜索页
2.未出现热搜和推荐，且去除热搜和推荐的开关处于关闭状态

### 日志

[log_哔哩哔哩.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15332558/log_.zip)

### 截图或录屏

![Uploading Screenshot_2024-05-16-17-21-01-52_149003a2d400f6adb210d7e357a3a646.jpg…]()
![Uploading Screenshot_2024-05-16-17-21-10-55_149003a2d400f6adb210d7e357a3a646.jpg…]()

**Comment by zjns** [comment]
修了，检查更新

**Comment by wanguiy** [comment]
把净化开屏推广关闭就可以了
