### ISSUE TITLE
bug: 播放视频闪退到上一个界面

### ISSUE THREAD

**Issue by Dogsdontevenneed** [BiliRoamingX/BiliRoamingX#253]
### 系统版本

coloros14

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.78.0

### 问题描述

播放视频闪退到上个界面，应该是上个 activity 吧

### 复现步骤

难以复现，不定时会出现，我也摸不准是怎么触发的

### 日志

[log_哔哩哔哩.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15359070/log_.zip)

**Comment by zjns** [comment]
有问题的基本都是Android 14，而且都是 native crash，看起来跟模块没有关系，用官方原版也会闪退吗？

**Comment by Dogsdontevenneed** [comment]
> 有问题的基本都是Android 14，而且都是原生崩溃，看起来跟模块没有关系，用官方原版也闪退吗？

官方不闪退的，我有一台设备是 a11，也是同样的情况
