### ISSUE TITLE
評論檢查時間

### ISSUE THREAD

**Issue by NeKoOuO** [BiliRoamingX/BiliRoamingX#254]
### 原因

8秒太長

### 功能简述

其實3~5秒就夠了，8秒有點太長了

### 功能逻辑

3~5秒

**Comment by zjns** [comment]
然而有时候 8 秒都不够

**Comment by zjns** [comment]
带图的评论就更不用说了

**Comment by NeKoOuO** [comment]
能夠分開檢查嗎？🤔
純文字和帶圖的

**Comment by zjns** [comment]
带图的是 15 秒

**Comment by zjns** [comment]
弹幕本来也能检查，但因为系统反应时间太慢了，一分钟以上，所以都去掉了

**Comment by NeKoOuO** [comment]
因為我之前用的模塊5秒檢查是沒問題的🤔

**Comment by NeKoOuO** [comment]
所以才有這個疑問
