### ISSUE TITLE
后台播放一直处于开启状态，无法关闭

### ISSUE THREAD

**Issue by bbcyz** [BiliRoamingX/BiliRoamingX#255]
### 系统版本

oneui5.1

### Android 版本

13

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

3.19.0

### 问题描述

任意视频二级菜单里面后台播放都处于开启状态，无法关闭

### 复现步骤

打开客户端，点击任意视频，二级菜单里面开关就是开启的状态，在点击也还是开启的状态

### 日志

[log_bilibili.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15368231/log_bilibili.zip)

### 解决办法

暂未发现

### 补充信息

https://www.bilibili.com/video/av1904556869，任意视频链接都如此

**Comment by zjns** [comment]
未按要求复现上传日志
