### ISSUE TITLE
feat: 请求开启评论区图片保存功能

### ISSUE THREAD

**Issue by mingqitianxia12138** [BiliRoamingX/BiliRoamingX#256]
### 原因

由于有些评论区图片并不能打开，导致官方功能并不实用，建议开启模块原有功能

### 功能简述

恢复模块图片保存功能

### 功能逻辑

打开大图保存

### 实现参考

开启模块原有功能即可

**Comment by zjns** [comment]
例如？

**Comment by mingqitianxia12138** [comment]
例如有些视频下面的评论图片是打不开的，只能看，而不能变成大图，所以也不能保存
