### ISSUE TITLE
bug: 首页过滤推荐内容失效

### ISSUE THREAD

**Issue by 2584191127** [BiliRoamingX/BiliRoamingX#261]
### 系统版本

鸿蒙4

### Android 版本

不知道

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.78.0

### 问题描述

如图所示，设置了按类型过滤，但还是有这些内容
![Screenshot_20240520_191543_tv danmaku bili](https://github.com/BiliRoamingX/BiliRoamingX/assets/78305714/88469c49-6483-4ada-a7b0-bf33d1719d8c)
![Screenshot_20240520_191605_tv danmaku bili](https://github.com/BiliRoamingX/BiliRoamingX/assets/78305714/7d2a71c6-7b30-4a24-baf0-4bcef23cf336)

### 复现步骤

设置首页推荐过滤，打开b站

### 日志

[log_哔哩哔哩.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15376349/log_.zip)

**Comment by zjns** [comment]
检查更新

**Comment by 2584191127** [comment]
> 检查更新

大佬能发个安装包吗，在应用内更新会被华为拦截

**Comment by zjns** [comment]
> > 检查更新
> 
> 大佬能发个安装包吗，在应用内更新会被华为拦截

麻烦看项目介绍 README.md
