### ISSUE TITLE
feat: 希望首页长按视频封面，里面的漫游屏蔽栏目可以隐藏

### ISSUE THREAD

**Issue by Dome-World** [BiliRoamingX/BiliRoamingX#262]
### 原因

很多时候长按首页视频是想添加到稍后再看，但目前菜单太长了，使得稍后再看那行不好按

### 功能简述&逻辑

可以隐藏去掉我不想看或者漫游屏蔽栏目

**Comment by zjns** [comment]
不长吧，官方的弹框也做了折叠处理。

**Comment by Dome-World** [comment]
> 不长吧，官方的弹框也做了折叠处理。

？什么折叠，我是说弹出来的菜单，官方只有一个我不想看，插件加了个漫游屏蔽，在显示大小为大的时候这个菜单上下就很长了，这个能控制功能的显示是最好的，要不稍后再看那行就不好按了
