### ISSUE TITLE
feat: [直播] 默认/流量下仅播声音，并设法使仅播声音切换按钮更易访问

### ISSUE THREAD

**Issue by Crystal-RainSlide** [BiliRoamingX/BiliRoamingX#263]
### 原因

默认仅播声音对于节省流量/小带宽下节省带宽会有帮助，也很适合各种音频直播。

如果启用默认仅播声音，就可能会经常需要临时查看画面，就会经常用到“仅播声音/播放画面”切换按钮。
但打开直播间右上角菜单后，可以看到，这个切换按钮位居第十，往往需要滑动才能看到，较难访问。

### 功能简述

- 支持 在进入直播间时，默认仅播声音
- 如果可能的话，支持 只有在流量下进入直播间时，默认仅播声音
- 提供一种或多种能够改善“仅播声音/播放画面”切换按钮的可访问性的办法

### 功能逻辑

- 　　默认仅播声音：进入直播间时，默认仅播声音
- 　流量下仅播声音：流量下进入直播间时，默认仅播声音
- “仅播声音”切换按钮：不管用什么办法，让它能被直接显示在刚打开的直播间右上角菜单中

### 实现参考

- 默认仅播声音：可以考虑在进入直播间时，代理点击仅播声音按钮？
- “仅播声音”切换按钮：
	- 如果能够支持修改按钮排序，就能让用户自行改善这一问题；
	- 否则，可以考虑改善菜单的排版，将所有功能按钮显示成两行；
	- 再者，可以简单地将此按钮置顶，排到第一个，仅用于配套“默认仅播声音”使用。

**Comment by zjns** [comment]
累了，不想折腾这么小众麻烦的事情
