### ISSUE TITLE
请求屏蔽大会员任务“观看剧集内容”读条

### ISSUE THREAD

**Issue by Pineapple-NINJA** [BiliRoamingX/BiliRoamingX#265]
### 原因

在“赚大积分”界面可以领取看10分钟剧集的任务，白嫖大会员，但是完成任务时会有一个非常有碍观瞻的读条。
![IMG_20240521_093555](https://github.com/BiliRoamingX/BiliRoamingX/assets/170381797/5cfe4ec8-ff28-4255-aa6a-89765ea278fc)

![IMG_20240521_091732](https://github.com/BiliRoamingX/BiliRoamingX/assets/170381797/f73e8302-71a8-449e-ab23-b8a69ebdd148)

### 功能简述

实际上这个读条可以通过选择“哔哩漫游x”→“视频详情页”→“屏蔽番剧页面广告”来隐藏，但这样会导致任务无法完成，请问是否可以在隐藏该读条的同时不影响任务完成呢？

### 功能逻辑

暂无

### 实现参考

大积分任务没有改版之前，是没有该读条但是可以完成任务的。
我是觉得这个读条挡屏幕实在过于逆天，阿b应该很快就会给修了吧，没想到一直没有。
最后感谢大佬一直以来的付出，我不太懂原理，这个功能如果实现起来比较麻烦就请无视吧，b站有朝一日也许会自己改……

**Comment by zjns** [comment]
这不是仅大会员的任务吗

**Comment by Pineapple-NINJA** [comment]
> 这不是仅大会员的任务吗

是的，现在的情况是每天做一下任务，每30天会员可以白嫖10天。
做这个“观看剧集内容”的任务，还能增加补番的动力（实测看港澳台区的动画也能完成任务），不过有读条挡屏幕就得不偿失了。

**Comment by do02fw** [comment]
> 这不是仅大会员的任务吗

我发到酷安了

**Comment by zjns** [comment]
> > 这不是仅大会员的任务吗
> 
> 我发到酷安了

?? 为什么要往酷安那个垃圾平台发？

**Comment by do02fw** [comment]
那要不你在里面加一些骂酷安的话，这样他们被骂了就不会用了

**Comment by zjns** [comment]
> 那要不你在里面加一些骂酷安的话，这样他们被骂了就不会用了

?? 你不发不就得了

**Comment by do02fw** [comment]
我为了得点粉丝

**Comment by do02fw** [comment]
你除非禁止酷安的用户使用，不然只要有安装包他们就能用

**Comment by Pineapple-NINJA** [comment]
> 我为了得点粉丝

如果是因为这个理由，这边建议尊重原作者劳动成果，转发资源最好事先取得原作者的同意。
或者只搬运明确表示不需要转载授权的作品。

**Comment by zjns** [comment]
1. 这个倒计时只在全屏时触摸才会显示，不影响观看体验
2. 优化开启屏蔽会员页广告后，依旧允许显示这个倒计时

@Pineapple-NINJA

**Comment by Pineapple-NINJA** [comment]
> 1. 这个倒计时只在全屏时触摸才会显示，不影响观看体验
> 2. 优化开启屏蔽会员页广告后，依旧允许显示这个倒计时
> 
> @Pineapple-NINJA

谢谢，我拿备用手机进行了测试，确实如你“1.”所说，看来我这里该读条不能正常隐藏是设备或者系统问题（Realme RMX3366; realme UI 5.0）。
我会尝试用别的手段解决问题。
