### ISSUE TITLE
请求屏蔽“最近”页面中“最近使用的小程序”一栏

### ISSUE THREAD

**Issue by Pineapple-NINJA** [BiliRoamingX/BiliRoamingX#267]
### 原因

B站app中，点击头像可以进入“最近”页面，这个页面还是比较实用的。
然而现在这个不经意间点开的、毫无价值的小程序一直挂在最显眼的位置，并且一周了也没有自动消除，影响美观的同时也遮挡了其它更有意义内容的显示。

### 功能简述

如图，希望可以屏蔽“最近使用的小程序”这一栏。
![240b849e3702a4baad47a4ec0cb4781](https://github.com/BiliRoamingX/BiliRoamingX/assets/170381797/f3b71ab8-6829-4481-9f07-cd7c7c77c550)

### 功能逻辑

也许可以在“哔哩漫游x”→“首页”菜单中添加一个有关屏蔽该模块的开关。

**Comment by Pineapple-NINJA** [comment]
毫不夸张地说，大佬的改版app的现有功能已经让我的日常b站使用体验提升了至少2000%，再一次表示感谢！

**Comment by do02fw** [comment]
我发到酷安了，啦啦啦啦
