### ISSUE TITLE
评论区图片的查看和直接保存feat: 

### ISSUE THREAD

**Issue by JankZhang** [BiliRoamingX/BiliRoamingX#271]
### 原因

评论区里面的图片不能打开，放大

### 功能简述

我评论区里的图片能打开，然后长按直接保存

### 功能逻辑

同上，谢谢大佬

### 实现参考

可能小红书可以

**Comment by zjns** [comment]
使用新版播放器

**Comment by JankZhang** [comment]
好像还是不行呀，点图片没反应









      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年5月23日(周四) 上午9:09写道:

  

 
使用新版播放器

**Comment by zjns** [comment]
图看不了，不行那就是你的问题

**Comment by JankZhang** [comment]
我删掉数据重新加载，在恢复备份前都可以看，不知道为什么恢复后就不行了，可能是某个功能矛盾了吗？









      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年5月23日(周四) 中午11:08写道:

  

 
图看不了，不行那就是你的问题

**Comment by JankZhang** [comment]
大佬，我是沙栾，我没重启









      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年5月23日(周四) 中午11:08写道:

  

 
图看不了，不行那就是你的问题
