### ISSUE TITLE
bug: 替换竖屏视频失效

### ISSUE THREAD

**Issue by Spike116** [BiliRoamingX/BiliRoamingX#272]
### 系统版本

coloros11.2

### Android 版本

11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.78

### 问题描述

替换竖屏视频失效

### 复现步骤

开启替换竖版视频和隐藏竖屏按钮后观看竖屏视频依然是官方版，重启也无用

### 日志

[log.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15419137/log.zip)

### 截图或录屏

![Screenshot_2024-05-23-23-28-22-86_149003a2d400f6adb210d7e357a3a646](https://github.com/BiliRoamingX/BiliRoamingX/assets/104405477/50f70593-67fd-45dc-80e7-d5404d7c7221)
![Screenshot_2024-05-23-23-28-29-51_149003a2d400f6adb210d7e357a3a646](https://github.com/BiliRoamingX/BiliRoamingX/assets/104405477/7d14de1a-a8b7-4b2a-b7c5-d4ee0e1c0f73)

**Comment by zjns** [comment]
怎么进来的？

**Comment by zjns** [comment]
复现步骤说清楚
