### ISSUE TITLE
bug: 偶尔遇到有视频黑屏，无法播放

### ISSUE THREAD

**Issue by RainTsal** [BiliRoamingX/BiliRoamingX#275]
### 系统版本

HyperOS

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.78

### 问题描述

点进视频无反应，黑屏。点击视频仍然无反应。但可以看评论区。视频无播放记录。不经常有偶尔遇到一两个视频是这样。遇到过几次。本版本才有

### 复现步骤

打开问题视频，黑屏，点击无反应。

### 日志

[log_哔哩哔哩.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15427981/log_.zip)

### 截图或录屏

https://github.com/BiliRoamingX/BiliRoamingX/assets/78639461/3fe5535b-8381-40bd-a3e7-d465e687065d

![图片_20240524131952](https://github.com/BiliRoamingX/BiliRoamingX/assets/78639461/c4afd28b-c395-4991-b162-102175d5d127)

### 解决办法

望大佬查看一下是什么问题，谢谢

### 补充信息

BV15HuyeVEGX

**Comment by zjns** [comment]
关闭禁止p2p上传，最近版本官方的播放器有bug，关闭p2p后，不能播放avid大于2147483647的视频

**Comment by wan0ge** [comment]
> 关闭禁止p2p上传，最近版本官方的播放器有bug，关闭p2p后，不能播放avid大于2147483647的视频

发现了与禁止p2p上传相关的相似问题，开启后播放杜比视界清晰度会一卡一卡的，能播放但限速，4K等清晰度正常，不知道是不是同一问题

**Comment by zjns** [comment]
7.80.0版本官方已修复此问题
