### ISSUE TITLE
打开时概率闪退

### ISSUE THREAD

**Issue by yuehongbaisu** [BiliRoamingX/BiliRoamingX#276]
### 系统版本

Flyme 10.5.0.0A

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.78.0

### 问题描述

打开时可能闪退

### 复现步骤

1.打开软件
2.发生闪退
3.再次打开正常进入

### 日志

[log_哔哩哔哩.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15430749/log_.zip)

**Comment by zjns** [comment]
已修复，等下个版本
