### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by 1451181528** [BiliRoamingX/BiliRoamingX#277]
### 系统版本

澎湃1.0.24.5.13.DEV

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.78.0

### 问题描述

闪退

### 复现步骤

使用一段时间后随机出现

### 日志

Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Redmi
[Device Model]: 23013RK75C
[Display]: UKQ1.230804.001 release-keys
[Android Version]: 14
[Android API Level]: 34
[System Locale]: zh_CN
[Process ID]: 6057
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: tv.danmaku.bili
[Version Name]: 7.78.0
[Version Code]: 7780300
[Target SDK]: 33
[Min SDK]: 23
[Error Type]: Native
[Crash Time]: 2024-05-24T20:30:56.213
[Stack Trace]:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Redmi/mondrian/mondrian:14/UKQ1.230804.001/V816.0.24.5.13.DEV:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2024-05-24 20:30:55.085991057+0800
Process uptime: 6862s
Cmdline: tv.danmaku.bili
pid: 6057, tid: 15610, name: Thread-65  >>> tv.danmaku.bili <<<
uid: 10272
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
signal 6 (SIGABRT), code 0 (SI_USER), fault addr --------
Abort message: 'stack corruption detected (-fstack-protector)'
    x0  0000000000000000  x1  0000000000003cfa  x2  0000000000000006  x3  0000007891d33f80
    x4  607372652c271f63  x5  607372652c271f63  x6  607372652c271f63  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  0000007a64c28ea8  x10 0000000000000001  x11 0000007a64ca5420
    x12 0000000066508879  x13 000000007fffffff  x14 0000000000fcbca2  x15 0000017308360444
    x16 0000007a64d10a18  x17 0000007a64ce8ea0  x18 0000007902162834  x19 00000000000017a9
    x20 0000000000003cfa  x21 00000000ffffffff  x22 000000001d8ea268  x23 00000000fae482e8
    x24 00000000e29d9728  x25 0000000000314af6  x26 0000000068d4e5d0  x27 0000000051079ea2
    x28 0000000000000000  x29 0000007891d34000
    lr  0000007a64c96164  sp  0000007891d33f60  pc  0000007a64c96190  pst 0000000000001000
10 total frames
backtrace:
      #00 pc 0000000000095190  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 1e3ca19bcae05c01b019c85f3f422e56)
      #01 pc 00000000000ab860  /apex/com.android.runtime/lib64/bionic/libc.so (__stack_chk_fail+24) (BuildId: 1e3ca19bcae05c01b019c85f3f422e56)
      #02 pc 00000000000338cc  /data/app/~~NbOQ5SyVpDoeJSiFLBAsPg==/tv.danmaku.bili-Os_pJThOm-vEZ2_Y9d5z1Q==/lib/arm64/libbili.so (BuildId: 41c22b6877c1daf5357ed3146c530e1bf02e6cf7)
      #03 pc 00000000000328a0  /data/app/~~NbOQ5SyVpDoeJSiFLBAsPg==/tv.danmaku.bili-Os_pJThOm-vEZ2_Y9d5z1Q==/lib/arm64/libbili.so (BuildId: 41c22b6877c1daf5357ed3146c530e1bf02e6cf7)
      #04 pc 0000000000034278  /data/app/~~NbOQ5SyVpDoeJSiFLBAsPg==/tv.danmaku.bili-Os_pJThOm-vEZ2_Y9d5z1Q==/lib/arm64/libbili.so (BuildId: 41c22b6877c1daf5357ed3146c530e1bf02e6cf7)
      #05 pc 000000000002e1cc  /data/app/~~NbOQ5SyVpDoeJSiFLBAsPg==/tv.danmaku.bili-Os_pJThOm-vEZ2_Y9d5z1Q==/lib/arm64/libbili.so (BuildId: 41c22b6877c1daf5357ed3146c530e1bf02e6cf7)
      #06 pc 000000000002497c  /data/app/~~NbOQ5SyVpDoeJSiFLBAsPg==/tv.danmaku.bili-Os_pJThOm-vEZ2_Y9d5z1Q==/lib/arm64/libbili.so (BuildId: 41c22b6877c1daf5357ed3146c530e1bf02e6cf7)
      #07 pc 000000000002461c  /data/app/~~NbOQ5SyVpDoeJSiFLBAsPg==/tv.danmaku.bili-Os_pJThOm-vEZ2_Y9d5z1Q==/lib/arm64/libbili.so (BuildId: 41c22b6877c1daf5357ed3146c530e1bf02e6cf7)
      #08 pc 00000000000fd134  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 1e3ca19bcae05c01b019c85f3f422e56)
      #09 pc 0000000000096ae4  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 1e3ca19bcae05c01b019c85f3f422e56)

**Comment by zjns** [comment]
有问题的都是Android 14，应该是B站适配问题

**Comment by 1451181528** [comment]
原版和哔哩漫游我都用过，没有出现过类似问题
