### ISSUE TITLE
feat: 请求在视频播放界面添加弹幕优选开关设置

### ISSUE THREAD

**Issue by MCyudix** [BiliRoamingX/BiliRoamingX#279]
### 原因

请求在视频播放界面添加弹幕优选开关设置
在视频中的弹幕设置中，如果开启弹幕优选，只能从设置内播放设置的弹幕设置中关闭

### 功能简述

快速开关

### 功能逻辑

将原弹幕优选设置的折叠更改为关闭，或将设置按钮放在长按（或三个点）菜单内，点击即可直接切换开关

**Comment by zjns** [comment]
麻烦，算了
