### ISSUE TITLE
在观看视频时可以进行ai视频总结

### ISSUE THREAD

**Issue by Alantemper** [BiliRoamingX/BiliRoamingX#280]
### 原因

可以用ai总结视频节省时间

### 功能简述

b站网页版可以进行ai视频总结，有没有可能调用这个功能总结视频内容

### 功能逻辑

在视频
![Screenshot_2024-05-25-16-11-31-288_tv danmaku bili](https://github.com/BiliRoamingX/BiliRoamingX/assets/108141718/848739b0-5721-4ecc-8f72-723af150fc45)
简介处长按菜单使用ai视频总结

### 实现参考

https://github.com/guozhigq/pilipala
pilipala这款第三方b站实现了这个功能，我不清楚Revanced方案能不能实现，不能就算了
![Screenshot_2024-05-25-16-09-19-406_com guozhigq pilipala](https://github.com/BiliRoamingX/BiliRoamingX/assets/108141718/543a4aa4-8daf-42d9-a435-c929017e8992)

**Comment by zjns** [comment]
有点意思，可以实现
