### ISSUE TITLE
使ai总结内时间可点击跳转

### ISSUE THREAD

**Issue by Alantemper** [BiliRoamingX/BiliRoamingX#281]
### 原因

大佬效率真高👍🏻但现在ai总结出的时间点无法跳转

### 功能简述

希望使用ai总结可以点击视频时间跳转相应位置

### 功能逻辑

![Screenshot_2024-05-26-11-40-18-218_tv danmaku bili](https://github.com/BiliRoamingX/BiliRoamingX/assets/108141718/f95ec606-c69c-4d95-9595-b9db1f34302a)
点击时间关闭菜单并跳转

**Comment by Alantemper** [comment]
还有个bug，如果视频没有简介，无法长按使用保存封面/ai总结功能

**Comment by zjns** [comment]
不易实现
