### ISSUE TITLE
“不锁定屏幕旋转方向”未生效

### ISSUE THREAD

**Issue by pasical** [BiliRoamingX/BiliRoamingX#282]
### 系统版本

hyperOS 1.0.6 / 原生安卓

### Android 版本

14 / 11

### 哔哩哔哩版本

HD 版

### 哔哩哔哩版本号

1.21.0

### 问题描述

前几天我提交了HD版竖屏模式的issue，如我所愿，我的需求被采纳。但是我今天把漫游X更新到最新版本后（因为之前有我自己注入的模块，当时嫌麻烦就没有第一时间更），发现该功能没有正常实现。我在平板和手机上都尝试了该功能，都成功复现。似乎我之前提供的解决问题的xposed模块没有公布源代码，暂时未知解决步骤。

### 复现步骤

_

### 日志

[info.json](https://github.com/BiliRoamingX/BiliRoamingX/files/15448049/info.json)
[log.txt](https://github.com/BiliRoamingX/BiliRoamingX/files/15448051/log.txt)

**Comment by zjns** [comment]
有效的，仔细看功能说明

**Comment by pasical** [comment]
> 有效的，仔细看功能说明

> 不知道是否是判定问题，在我测试的视频： https://b23.tv/KuTIJa5 以及 https://b23.tv/Ijc8SqX 中并未生效。我也寻找了漫游设置和原版设置，都没有任何遗漏的开关。HD版没有竖屏模式入口，不知道是否和这个有关。![Screenshot_2024-05-27-09-12-13-684_tv.danmaku.bili-edit.jpg](https://github.com/BiliRoamingX/BiliRoamingX/assets/112304778/528a26dd-ca6d-4d90-ba12-dde4245942f7)

![Screenshot_2024-05-27-09-13-09-198_tv.danmaku.bilibilihd-edit.jpg](https://github.com/BiliRoamingX/BiliRoamingX/assets/112304778/699a1dd2-2fb4-4e10-958d-d4fd081c48b9)


同时HD版中也没有原版的旋转手势。
以下是我想要的效果
![IMG_20240527_092016.jpg](https://github.com/BiliRoamingX/BiliRoamingX/assets/112304778/43097e36-bdac-4a7c-80b6-6eca63125d57)

**Comment by zjns** [comment]
![Screenshot_20240527_094905_HD.png](https://github.com/BiliRoamingX/BiliRoamingX/assets/10793522/d4030192-c757-4b62-8afa-0e2308bb35e2)

？？我这里是可用的

**Comment by pasical** [comment]
> ？？我这里是可用的

怪🤔，我再换不同环境试试

**Comment by zjns** [comment]
> > ？？我这里是可用的
> 
> 怪🤔，我再换不同环境试试

可能是鸿蒙的问题，如果是，我没有鸿蒙设备，无力解决

**Comment by pasical** [comment]
> > > ？？我这里是可用的
> > 
> > 怪🤔，我再换不同环境试试
> 
> 可能是鸿蒙的问题，如果是，我没有鸿蒙设备，无力解决

不是鸿蒙，测试的设备是MIUI和chromeOS的安卓容器，我等下在真正的原生安卓试试

**Comment by zjns** [comment]
> > > > ？？我这里是可用的
> > > 
> > > 怪🤔，我再换不同环境试试
> > 
> > 可能是鸿蒙的问题，如果是，我没有鸿蒙设备，无力解决
> 
> 不是鸿蒙，测试的设备是MIUI和chromeOS的安卓容器，我等下在真正的原生安卓试试

系统设置的自动旋转开了没/方向锁定关了没

**Comment by pasical** [comment]
> 系统设置的自动旋转开了没/方向锁定关了没

我都是检查过的

**Comment by pasical** [comment]
https://github.com/BiliRoamingX/BiliRoamingX/assets/112304778/bb6d83de-73d0-4f32-95d2-d931ad13b294

**Comment by pasical** [comment]
上述过程都有尝试旋转手机

**Comment by zjns** [comment]
找到问题了，你没登录，或者用最新ci版本打包

**Comment by pasical** [comment]
> 找到问题了，你没登录，或者用最新ci版本打包

https://github.com/BiliRoamingX/BiliRoamingX/assets/112304778/725ac403-d302-4b6e-8230-4d753e1f07ce

**Comment by zjns** [comment]
登录就行了，ci版本指这个 https://github.com/BiliRoamingX/BiliRoamingX/actions

**Comment by pasical** [comment]
> 登录就行了，ci版本指这个 https://github.com/BiliRoamingX/BiliRoamingX/actions

噢噢，好的感谢❤️
