### ISSUE TITLE
恢复模块的禁止首页刷新功能

### ISSUE THREAD

**Issue by Helvetica1963** [BiliRoamingX/BiliRoamingX#285]
### 原因

因为原版客户端自带了禁止首页刷新的功能，所以新版的将其去除。然而客户端自带的这一功能经常失效，退出视频后，首页刷新没有被阻止。

### 功能简述

我希望通过该模块来实现禁止首页刷新，这样做会比客户端本身的功能更为可靠。可以说原版客户端为了恰流量脸都不要了

### 功能逻辑

在漫游X设置中恢复禁止首页刷新的开关

**Comment by zjns** [comment]
1.21.0版本开始已经对官方这个功能进行了补强，只要官方选项关闭了自动刷新，模块就会依旧处理。

**Comment by zjns** [comment]
主要是一个功能不能有两个开关，不然容易引起困扰和冲突。
