### ISSUE TITLE
bug: 评论区图片无法点开，也无法长按保存

### ISSUE THREAD

**Issue by yonghuming8** [BiliRoamingX/BiliRoamingX#286]
### 系统版本

origin os 4

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.78.0

### 问题描述

评论区的图片没办法点击打开查看大图，点了没反应，长按也不能保存

### 复现步骤

1.打开评论区
2.点击图片
3.无法查看大图或任何操作，点击无反应。

### 日志

[log_哔哩哔哩.zip](https://github.com/BiliRoamingX/BiliRoamingX/files/15469989/log_.zip)

**Comment by Norca0721** [comment]
使用新版播放器即可解决
