### ISSUE TITLE
feat: 增大直播间弹幕区域宽度

### ISSUE THREAD

**Issue by msm8976** [BiliRoamingX/BiliRoamingX#291]
### 原因

在默认布局中，右下角滚动横幅的宽度不会显示弹幕，即使通过模块屏蔽后该处宽度仍为空白，无法显示内容，有效显示范围只有图中左侧红色框
![弹幕内容有效区域](https://github.com/BiliRoamingX/BiliRoamingX/assets/32473245/207265f3-aa41-4094-83e2-01547c997632)

### 功能简述

增大直播间弹幕区域宽度

### 功能逻辑

当启用屏蔽滚动横幅功能后，相应增大直播间弹幕区域宽度

### 实现参考

目前没有找到该处宽度具体是在哪里控制的，但可以通过在bili_live_room_business_interaction_view_v2.xml内id为danmaku_list_area的linearlayout或父布局中添加layout_marginRight属性间接解决。在我的设备上计算出的合适数值为-76dp，不清楚会不会在不同设备或dpi下产生错位，最好的方法还是找到右边距左移是怎么控制的然后删掉
![目前解决方式](https://github.com/BiliRoamingX/BiliRoamingX/assets/32473245/1c4055c8-2750-4a85-b4a2-441a9a9ff1d5)
![实现效果](https://github.com/BiliRoamingX/BiliRoamingX/assets/32473245/02f74f1a-2238-4b3f-80c1-30475c6b6515)

**Comment by zjns** [comment]
还要在代码里面判断，好麻烦
