### ISSUE TITLE
feat: 新版播放器状态栏沉浸

### ISSUE THREAD

**Issue by lr-tony** [BiliRoamingX/BiliRoamingX#294]
### 原因

新版播放器状态栏默认常驻（黑色一条）无法沉浸自动收回隐藏
旧版播放器可以状态栏沉浸体验差

### 功能简述

打开视频时状态栏自动沉浸

### 功能逻辑

拍视频时状态栏自动沉浸，下滑状态栏显示

**Comment by zjns** [comment]
官方反馈
