### ISSUE TITLE
bug: 开启优选cdn后部分直播间无法播放以及默认画质问题

### ISSUE THREAD

**Issue by recycle007** [BiliRoamingX/BiliRoamingX#295]
### 系统版本

h2os

### Android 版本

10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.80.0

### 问题描述

1，开启优选cdn后部分直播间比如https://b23.tv/g00pI36原画主线路无法播放，切换其他线路正常
2，画质选项里选杜比视界后看hdr视频不能默认hdr，导致这两个只能二选一
3，希望能增加修改直播间弹幕粗细的选项，现在直播间默认都是比视频要粗的粗体。。

### 复现步骤

100%复现

### 日志

无

**Comment by zjns** [comment]
第三点反馈给官方，而不是这。

**Comment by zjns** [comment]
> > 第一点无法复现。
> 
> 画质有选择原画吗，没有开启原画默认超清我这也正常，就是原画+主线路会无法加载，现在还是这样

没看到提issue的要求吗？你以为人人都跟你一样是吧？复现日志呢？
