### ISSUE TITLE
bug: 1.22.0更换后的过签方式导致伪官签哔哩哔哩无法正常运行

### ISSUE THREAD

**Issue by huniangitb** [BiliRoamingX/BiliRoamingX#296]
### 系统版本

澎湃1.0.7.0

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.80.0

### 问题描述

伪官签会导致APP启动卡第一屏，上个版本则不会有这个问题。单独进行v1签名后不进行其他操作,不会导致卡第一屏，正常进入哔哩哔哩

### 复现步骤

将注入后的哔哩哔哩V1签名，然后使用官方rsa签名替换哔哩哔哩内的rsa签名,安装后卡第一屏.

### 日志

卡第一屏都分享不了日志

**Comment by huniangitb** [comment]
![Uploading Screenshot_2024-05-31-23-27-50-834_bin.mt.plus.jpg…]()

**Comment by huniangitb** [comment]
![1000094550](https://github.com/BiliRoamingX/BiliRoamingX/assets/164629750/0d31eddb-37e5-4646-8989-1f19d3ad0cb5)

**Comment by zjns** [comment]
伪官签有啥用，微信分享？

**Comment by huniangitb** [comment]
微信，QQ分享之类的，不伪官签的话，会弹非官方应用。否则只能通过复制链接粘贴分享了。

**Comment by zjns** [comment]
把 META-INF 目录下的 .SF 和 .MF 后缀文件删掉

**Comment by huniangitb** [comment]
删除这两个文件后，Mt管理器显示签名状态变为未签名,安装后能正常启动,但分享依旧提示非官方应用(官方rsa签名已经替换过去)

**Comment by zjns** [comment]
> 删除这两个文件后，Mt管理器显示签名状态变为未签名,安装后能正常启动,但分享依旧提示非官方应用(官方rsa签名已经替换过去)

那就重新先用v2签一次名，然后把RSA放进去试试

**Comment by huniangitb** [comment]
用v2签名的话，伪造的v1签名就没用了,系统和软件只校验v2签名,除非伪造v2签名，v2签名要伪造的话需要找APK 签名分块(相对v1比较麻烦)，这种卡第一屏的现象只出现在签名校验不通过的情况下，大概率是新版过签方案导致的奇妙问题

**Comment by zjns** [comment]
> 用v2签名的话，伪造的v1签名就没用了,系统和软件只校验v2签名,除非伪造v2签名，v2签名要伪造的话需要找APK 签名分块(相对v1比较麻烦)，这种卡第一屏的现象只出现在签名校验不通过的情况下，大概率是新版过签方案导致的奇妙问题

那试一下先用v2+v3签一次名，再把rsa放进去，现在的过签方式对签名要求是更低的

**Comment by huniangitb** [comment]
目前想让微信QQ不报非官方应用的话，只能在核心破解勾选安装应用始终使用已安装应用签名，也就是先安装原版应用，在安装注入后的应用，或者用算法助手注入微信qq,使微信，QQ只能获得官方签名。v2+v3一样,当签名校验过不去时，就是卡第一启动图,感觉主要是新模块的过签方案和伪官签冲突

**Comment by forchannot** [comment]
核心破解这个我试过了，不知道为啥并没有用

**Comment by forchannot** [comment]
目前用simplehookr临时解决了

**Comment by StarWishsama** [comment]
> 目前用simplehookr临时解决了

想请教一下 hook 的是哪个方法
