### ISSUE TITLE
bug: 启动图自定义不了

### ISSUE THREAD

**Issue by huwanbin0** [BiliRoamingX/BiliRoamingX#297]
### 系统版本

oringinOS4

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.80.0

### 问题描述

启动图自定义不了

### 复现步骤

1打开哔哩哔哩
2不显示自定义的启动图

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/15515771/log_.zip)

**Comment by zjns** [comment]
无法复现，图片有问题吧
