### ISSUE TITLE
最新版本自由复制失效了bug: 

### ISSUE THREAD

**Issue by Qing-Novel** [BiliRoamingX/BiliRoamingX#300]
### 系统版本

鸿蒙2

### Android 版本

安卓10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.80.0

### 问题描述

已确认x设置里开启了去除长按复制和开启自由复制，但评论区无法自由复制

### 复现步骤

1、安装软件
2、x设置里开启了去除长按复制和开启自由复制
3、找一个视频
4、进入评论区进行复制

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/15521542/log_.zip)

### 截图或录屏

https://github.com/BiliRoamingX/BiliRoamingX/assets/136884931/c95dc5a0-1764-49c9-97d8-389be5fa1ca0

**Comment by zjns** [comment]
功能正常，无法复现

**Comment by Qing-Novel** [comment]
> 功能正常，无法复现

我鸿蒙4也这个问题。。。是我没给什么权限导致的吗。。。。

**Comment by zjns** [comment]
> > 功能正常，无法复现
> 
> 我鸿蒙4也这个问题。。。是我没给什么权限导致的吗。。。。

我看你没用我的预构建包，用我的预构建包试试

**Comment by cxw620** [comment]
这不是正常吗, 点那个复制就弹出来了()

**Comment by Qing-Novel** [comment]
> 这不是正常吗, 点那个复制就弹出来了()

好吧，我刚用x版，还以为跟漫游那样，那没事了。。。
