### ISSUE TITLE
bug: 评论区图片无法点击放大。

### ISSUE THREAD

**Issue by zheliu13** [BiliRoamingX/BiliRoamingX#306]
### 系统版本

orgin os4

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.80.0

### 问题描述

评论区图片无法点击放大。
Comment area image cannot be enlarged by clicking

### 复现步骤

点击评论区图片时，无论单机或者双击，图片无反应。

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/15543095/log_.zip)

### 截图或录屏

https://github.com/BiliRoamingX/BiliRoamingX/assets/171654317/ba7170f9-a51e-4ef5-af00-578a60667864

https://github.com/BiliRoamingX/BiliRoamingX/assets/171654317/ed5ea886-ccc4-4ec3-b5ec-9e0ef6c5dc38

**Comment by zjns** [comment]
看版本说明 https://github.com/BiliRoamingX/BiliRoamingX/releases/latest
