### ISSUE TITLE
bug: 打开有数字藏品的UP主空间会崩溃

### ISSUE THREAD

**Issue by Galaxy240604** [BiliRoamingX/BiliRoamingX#307]
### 系统版本

hyperOS1.0.1.0

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.80.0

### 问题描述

打开up的主页。主页有数字藏品的会崩溃。会崩溃的是我用小米平板5Pro下载同样一个漫游x版本。
手机同一个版本不会崩溃，但用平板同一个版本就会崩溃。

### 复现步骤

1.打开任意有动态数字产品up的空间。
2.打开空间。APP闪退。

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/15543967/log_.zip)

### 截图或录屏

https://github.com/BiliRoamingX/BiliRoamingX/assets/171660266/d1ceda94-f0d9-4efd-9d65-8a3aa0af1060

### 补充信息

打开up的主页。主页有数字藏品的会崩溃。会崩溃的是我用小米平板5Pro下载同样一个漫游x版本。
手机同一个版本不会崩溃，但用平板同一个版本就会崩溃。

**Comment by zjns** [comment]
用官方原版试试

**Comment by Galaxy240604** [comment]
我刚才用过官方原版试过了，也是同样的问题。应该是官方的问题。

**Comment by zjns** [comment]
那就给官方反馈看看
