### ISSUE TITLE
偶尔崩溃

### ISSUE THREAD

**Issue by xin-j24** [BiliRoamingX/BiliRoamingX#311]
### 系统版本

originos4

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

1.22.1

### 问题描述

刷视频偶然崩溃重启

### 复现步骤

刷视频偶尔崩溃

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/15737524/log_.zip)

**Comment by zjns** [comment]
非模块问题

**Comment by zjns** [comment]
用这个修复版本看看 https://github.com/BiliRoamingX/BiliRoamingX-PreBuilds/releases/latest
