### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by bingcha12138** [BiliRoamingX/BiliRoamingX#313]
### 原因

手机全屏播放两边会有黑边，每次都需要手动选择拉伸

### 功能简述

能否新出一个功能能默认调整画面尺寸？

### 功能逻辑

b站播放器设置
![fffb09c6a91fcd9809418f0f9c426a9](https://github.com/BiliRoamingX/BiliRoamingX/assets/90013464/570b8b55-0557-49b6-bbf7-f0fdbf8a5f97)
![583be16120b0fb5cbd0209ffd88ce2c](https://github.com/BiliRoamingX/BiliRoamingX/assets/90013464/8acebf47-5fe8-4c05-bb78-dff58caab6f7)

**Comment by zjns** [comment]
已经有这功能了，漫游x设置搜索 缩放
