### ISSUE TITLE
bug: play版 首页-过滤推荐内容-按关键词过滤-up主 功能不生效

### ISSUE THREAD

**Issue by tushanmumu** [BiliRoamingX/BiliRoamingX#315]
### 系统版本

MIUI 12

### Android 版本

9

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

3.19.1

### 问题描述

首页-过滤推荐内容-按关键词过滤-up主 功能不生效

### 复现步骤

首页-过滤推荐内容-按关键词过滤-up主 功能不生效

### 日志

[log_bilibili.zip](https://github.com/user-attachments/files/15780596/log_bilibili.zip)

**Comment by do02fw** [comment]
自己编译每日构建版就解决了
