### ISSUE TITLE
feat: 屏蔽动态-关注中偶发的非最新视频

### ISSUE THREAD

**Issue by msm8976** [BiliRoamingX/BiliRoamingX#319]
### 原因

在某些情况下（通常为一段时间内未刷新动态页面，或间隔一段时间冷启动APP），首次刷新动态-关注时，首条内容会是已关注UP主发布的非最新视频（正常视频，非广告视频金主投流，但可能是类似逻辑），再次刷新后消失。触发该现象前，底栏动态按钮通常会显示该UP主头像。

### 功能简述

尝试屏蔽该类视频

### 功能逻辑

以下为相关日志：[log.txt](https://github.com/user-attachments/files/15824107/log.txt)
底栏动态按钮头像数据来源于com.bapis.bilibili.app.dynamic.v1.DynRedReply返回
首次com.bapis.bilibili.app.dynamic.v2.DynAllReq请求中，包含tab_recall相关数据，导致返回的首条内容为非最新视频

### 实现参考

屏蔽com.bapis.bilibili.app.dynamic.v1.DynRed 似乎已经屏蔽了？
com.bapis.bilibili.app.dynamic.v2.DynAllReq中删除tab_recall相关数据

**Comment by zjns** [comment]
既然你已经弄清楚了实现，PR welcome。
