### ISSUE TITLE
通知转简体

### ISSUE THREAD

**Issue by Tovke** [BiliRoamingX/BiliRoamingX#321]
### 原因

![Screenshot_2024-06-15-20-22-06-870_com bilibili app in](https://github.com/BiliRoamingX/BiliRoamingX/assets/127712533/cd03dd73-49d9-4c7c-9a3f-1091fdb221a3)
![Screenshot_2024-06-15-20-34-07-133_com bilibili app in](https://github.com/BiliRoamingX/BiliRoamingX/assets/127712533/b4350f02-ef47-4193-b50b-cdd44a8584b1)

### 功能简述

希望能够转换成简体中文

### 功能逻辑

如果有个开关就好了

**Comment by Tovke** [comment]
![Uploading Screenshot_2024-06-15-20-34-07-133_com.bilibili.app.in.jpg…]()

**Comment by zjns** [comment]
用粉版不就好了
