### ISSUE TITLE
bug: 开启原生媒体通知后直播小窗播放退出 bili 后闪退

### ISSUE THREAD

**Issue by lightsummer233** [BiliRoamingX/BiliRoamingX#322]
### 系统版本

helluvaOS/hentaiOS 14（可以忽略，试了 bili 官方的没问题）

### Android 版本

14

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

3.19.1

### 问题描述

直播小窗播放退出 bili 后闪退

### 复现步骤

1.随意打开一个直播
2.小窗播放
3.上滑退出 bili
4.crash

### 日志

[data_app_crash@1718523687441.txt](https://github.com/user-attachments/files/15856573/data_app_crash%401718523687441.txt)

### 补充信息

BiliRoamingX 1.22.4

**Comment by zjns** [comment]
什么魔改系统，无法复现

**Comment by lightsummer233** [comment]
> 什么魔改系统，无法复现

不是我系统的问题，我在 avd 上可以复现（要 a15 的 avd，安全补丁啥的高）
以及大概是原生媒体通知的问题

**Comment by lightsummer233** [comment]
顺带可以补点信息
我设备的
![Screenshot_20240616-174337](https://github.com/BiliRoamingX/BiliRoamingX/assets/93428659/536fe7e8-0f8d-4b30-922b-973961fbb35e)
测试使用的 avd
![clipboard_2024-06-16_17-44](https://github.com/BiliRoamingX/BiliRoamingX/assets/93428659/0e4e2a55-eee8-4bc0-bd31-01f1f1c2f616)

**Comment by zjns** [comment]
修好了，AOSP某个时间点后改了私有字段的名称

**Comment by lightsummer233** [comment]
> 修好了，AOSP某个时间点后规范了私有字段的名称，CI版本试试看

好

**Comment by lightsummer233** [comment]
没问题了，可以 close as complete 了）
