### ISSUE TITLE
无法获取最新更新

### ISSUE THREAD

**Issue by ghjjvbjj** [BiliRoamingX/BiliRoamingX#325]
### 系统版本

澎湃

### Android 版本

14

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

3.19.1

### 问题描述

无法更新，显示有1.22.4新版本，但是点击之后显示更新失败

### 复现步骤

1.打开关于
2.点击获取更新
3.显示获取更新失败

### 日志

[log_bilibili.zip](https://github.com/user-attachments/files/15912670/log_bilibili.zip)

**Comment by do02fw** [comment]
自己编译

**Comment by ghjjvbjj** [comment]
无ci构建好的集成包吗？

**Comment by do02fw** [comment]
看我的存储库，有编译方法

**Comment by zjns** [comment]
截个图嘞？有更新的截图和失败的截图

**Comment by do02fw** [comment]
可能是连接不到github，所以没办法更新，建议检查网络或者手动更新

**Comment by zjns** [comment]
无法复现

**Comment by ghjjvbjj** [comment]
> 无法复现

没有构建好的3.19.2的1.22.4的集成包吗？
