### ISSUE TITLE
bug: 搜索特定词语之后会闪退

### ISSUE THREAD

**Issue by NaNaChiSama** [BiliRoamingX/BiliRoamingX#326]
### 系统版本

ColorOS 14

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.0.0

### 问题描述

如题，当搜索特定词语之后会闪退，比如School Days，日在校园，缘之空，出包女王等原本就被B站戒严搜不出来东西的词语，应该不是B站自己的问题（大概）

### 复现步骤

1.打开哔哩哔哩
2.搜索

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/15921374/log_.zip)

### 补充信息

提一嘴不相干的，上次反馈的竖屏模式开启广告屏蔽后依旧会刷到广告的bug好像依旧没有修复，关于日志，我后续已经在[之前那条Issues](https://github.com/BiliRoamingX/BiliRoamingX/issues/204)下面上传了，可能是我不小心关闭了Issues导致没看见吧

**Comment by do02fw** [comment]
我测试8.1.0自编译的不会闪退，你可以试试我这个版本，地址 https://1008611.online，我自建的服务器
