### ISSUE TITLE
feat: 禁用首页推荐上滑刷新

### ISSUE THREAD

**Issue by msm8976** [BiliRoamingX/BiliRoamingX#333]
### 原因

首页推荐只会保留最近两次加载的推荐内容，继续上滑会刷新显示新的内容，而不是显示此前推荐的内容
例如打开APP默认加载了一次推荐内容，手动下滑刷新两次，此时上滑无法查看最初的推荐内容

### 功能简述

首页上滑时禁用自动刷新，或显示完所有已加载的数据后再刷新新的内容

### 功能逻辑

添加switch

### 实现参考

不知道能否通过ab_test实现，如果不行应该很麻烦

**Comment by zjns** [comment]
没啥意义，浪费时间
