### ISSUE TITLE
bug: 动态页屏蔽UID太多，导致动态消失

### ISSUE THREAD

**Issue by wumingxiaozu159** [BiliRoamingX/BiliRoamingX#335]
### 系统版本

coloros 11

### Android 版本

11

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.0.0

### 问题描述

1.  动态頁里的按关键词屏蔽的UID添加超过130个以上时，保存后只会保留130个UID
2.  动态頁屏蔽过多时，动态頁里就会出现空白，没有动态，刷新也无法消除此Bug

### 复现步骤

1.  打开  软件→我的→设置→哔哩漫游X→动态頁→按关键词过滤
2.  点击UID旁边的添加，使添加的UID数量大于130个以上，点击保存，重新进入这一页，就会发现被保存的UID只有130个
3.  在当你被屏蔽的UID太多时，且这些UID都是你关注的，在  首页→动态  刷新时，就会出现空白，没有任何一个动态

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16036533/log_.zip)

### 截图或录屏

![Screenshot_2024-06-29-04-13-26-45](https://github.com/BiliRoamingX/BiliRoamingX/assets/109326335/51d70071-5e0b-4fb3-954d-d4a00d76e760)

**Comment by zjns** [comment]
？？这种情况不应该直接取消关注吗，还有屏蔽的太多导致第一页空白，后面的页自然无法触底加载
