### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by han5211506** [BiliRoamingX/BiliRoamingX#336]
### 系统版本

澎湃OS

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.0.0

### 问题描述

页面不能加载，刷新或重置都没有变化，其他软件正常

### 复现步骤

https://github.com/BiliRoamingX/BiliRoamingX/assets/65791439/8faf52bc-245e-48f2-a93e-05a3509d78bf

### 日志

无法分享日志，点击无反应

**Comment by zjns** [comment]
没有日志我无能为力，卸载重装试试

**Comment by zjns** [comment]
还有，禁用那些奇奇怪怪的magisk模块和xposed插件试试
