### ISSUE TITLE
评论无法加载bug: 

### ISSUE THREAD

**Issue by han5211506** [BiliRoamingX/BiliRoamingX#337]
### 系统版本

澎湃OS

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.0.0

### 问题描述

视频正常播放评论刷不出来

https://github.com/BiliRoamingX/BiliRoamingX/assets/65791439/843d40c8-9c27-4eda-a53d-12afa8c78bc3

### 复现步骤

https://github.com/BiliRoamingX/BiliRoamingX/assets/65791439/cc6efe03-c9a8-4d58-89f6-9db109669574

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16060895/log_.zip)

### 截图或录屏

Uploading Screenrecorder-2024-07-02-10-23-58-126.mp4…

**Comment by zjns** [comment]
b站服务器问题或者网络问题，现在还这样？
