### ISSUE TITLE
 bug: 新版播放器里普通视频没有会员画质试看

### ISSUE THREAD

**Issue by boshaoting** [BiliRoamingX/BiliRoamingX#338]
### 系统版本

澎湃 os，红米 k50，天玑 8100

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.0.0 和 7.80.0 和 7.77.0 都试了

### 问题描述

在新版播放器里，点击视频播放页的大会员画质功能，没法试看，（不过番剧的会员画质是可以的）

### 复现步骤

1. 打开漫游设置中的新版播放器和大会员画质无限试看功能
2. 打开任意一个视频并选择高清晰度

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16088156/log_.zip)

### 截图或录屏

https://github.com/BiliRoamingX/BiliRoamingX/assets/83106463/e3179ac8-807d-4320-892d-fe7201f52a5d

### 解决办法

用旧版播放器是有高清的，但保存笔记图片的功能就没了，可以把 长按图片保存 功能恢复，俩功能绑一起

### 补充信息

BV1Q1421f7m2 这个视频可以确定没有 60 帧

**Comment by zjns** [comment]
正如功能描述所说，能否试用取决于官方接口，像我的小号这个视频新版播放器就可以试用，旧版播放器将来某天肯定会被完全移除，所以官方的bug我肯定不会管的。
