### ISSUE TITLE
希望增加屏蔽搜索页中相关评论的功能

### ISSUE THREAD

**Issue by xiegongzi** [BiliRoamingX/BiliRoamingX#340]
### 原因

搜索页中出现过相关评论
![Screenshot_2024-07-05-19-44-33-094_tv danmaku bili](https://github.com/BiliRoamingX/BiliRoamingX/assets/167599062/4d9c1326-edcf-494a-9edc-81cd3fba5d7a)

### 功能简述

屏蔽搜索页中相关评论

### 功能逻辑

在搜索页中增加屏蔽相关评论功能

**Comment by zjns** [comment]
调试模式复现分享日志至此

**Comment by github-24** [comment]
> 调试模式复现分享日志至此

同求！

**Comment by zjns** [comment]
> > 调试模式复现分享日志至此
> 
> 同求！
> [log_哔哩哔哩.zip](https://github.com/user-attachments/files/16123732/log_.zip)
> 

日志并未包含相关评论

**Comment by github-24** [comment]
> > > 调试模式复现分享日志至此
> > 
> > 
> > 同求！
> > [log_哔哩哔哩.zip](https://github.com/user-attachments/files/16123732/log_.zip)
> 
> 日志并未包含相关评论

我不知道怎么操作，就是搜索视频完成的界面包含评论在里面，占据屏幕显示空间，能否像旧版一样只显示视频？
![Uploading IMG_20240708_143937.jpg…]()

**Comment by zjns** [comment]
> 我不知道怎么操作，就是搜索视频完成的界面包含评论在里面，占据屏幕显示空间，能否像旧版一样只显示视频？

Issue 说的相关评论卡片是指这个，应该还在灰度，你这明显不是
![f46ff7ca50cb604d864d8de1905297a3](https://github.com/BiliRoamingX/BiliRoamingX/assets/10793522/1e10f87b-5fe9-4dd6-9ba6-1984314a4bbd)

**Comment by github-24** [comment]
> > 我不知道怎么操作，就是搜索视频完成的界面包含评论在里面，占据屏幕显示空间，能否像旧版一样只显示视频？
> 
> Issue 说的相关评论卡片是指这个，应该还在灰度，你这明显不是 ![f46ff7ca50cb604d864d8de1905297a3](https://private-user-images.githubusercontent.com/10793522/346547199-1e10f87b-5fe9-4dd6-9ba6-1984314a4bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDEwOTMsIm5iZiI6MTcyMDQ0MDc5MywicGF0aCI6Ii8xMDc5MzUyMi8zNDY1NDcxOTktMWUxMGY4N2ItNWZlOS00ZGQ2LTliYTYtMTk4NDMxNGE0YmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDEyMTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0OWUyMDBkMTAzNjZmZTBiMzc0MTllYzljY2M1MDBlNTU4Y2E1OTFhMzY1MjE0MTIwNDhkOGJkM2VmYTBjZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VCB94H9mc9tB3hoTSl8HrNUCMoSUyAIVWDEty9Qu_DQ)

搞错了，那我这个能去除吗
