### ISSUE TITLE
feat: 移除播放界面“AI生成”提示。

### ISSUE THREAD

**Issue by MiRinChan** [BiliRoamingX/BiliRoamingX#341]
### 原因

于 8.0.0（及以上）观看部分视频时会在左下角显示“AI生成”的字样。

如 https://www.bilibili.com/video/av1606010680

![Screenshot_20240706-001925](https://github.com/BiliRoamingX/BiliRoamingX/assets/148533509/0a018db3-808d-4196-a394-d83265c3c401)

### 功能简述

此功能启用后应不显示“AI生成”水印字样。

### 功能逻辑

设置一种开关，打开后此功能启用。

**Comment by zjns** [comment]
没有单独开关，受控与“移除视频浮窗”
