### ISSUE TITLE
bug: 更新到 1.22.5 后分享到微信的功能不见了

### ISSUE THREAD

**Issue by Cywair** [BiliRoamingX/BiliRoamingX#342]
### 系统版本

CRDROID 10.5

### Android 版本

14

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

3.19.2

### 问题描述

更新到最新版后，点击分享已经没有分享到微信的入口了。记得之前作者大大做了一个判断如果是官签就开放分享到微信的功能，但是现在连入口都不见了。

### 复现步骤

1. 打开一个视频
2. 点击分享
3. 找不到 微信 按钮

### 日志

[log_bilibili.zip](https://github.com/user-attachments/files/16112491/log_bilibili.zip)

**Comment by zjns** [comment]
官方屏蔽的，要分享齐全就不要用play版。

**Comment by Cywair** [comment]
> 官方屏蔽的，要分享齐全就不要用play版。

好的，感谢回复
