### ISSUE TITLE
备份和恢复配置失败

### ISSUE THREAD

**Issue by lxg2001** [BiliRoamingX/BiliRoamingX#343]
### 系统版本

小米14 HyperOS 1.0.42.0 UNCCNXM

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.3.0

### 问题描述

备份和恢复配置全部失败

### 复现步骤

点击备份或者恢复，全部失败

### 日志

日志也不能分享

### 截图或录屏

https://github.com/BiliRoamingX/BiliRoamingX/assets/158118201/dd752498-a02e-4911-94da-2284428fe05e

**Comment by zjns** [comment]
无法复现，冷重启APP，换文件夹这些操作都试过了？

**Comment by lxg2001** [comment]
> 无法复现，冷重启APP，换文件夹这些操作都试过了？

都试过了，都没用，不管是从github上下载的还是自己打包的，都有这个问题

**Comment by zjns** [comment]
> > 无法复现，冷重启APP，换文件夹这些操作都试过了？
> 
> 都试过了，都没用，不管是从github上下载的还是自己打包的，都有这个问题

有没有装一些奇奇怪怪的magisk模块或者Xposed插件？

**Comment by lxg2001** [comment]
> > > 无法复现，冷重启APP，换文件夹这些操作都试过了？
> > 
> > 都试过了，都没用，不管是从github上下载的还是自己打包的，都有这个问题
> 
> 有没有装一些奇奇怪怪的magisk模块或者Xposed插件？

我都没有root
