### ISSUE TITLE
可以去除搜索结果页的评论显示吗？

### ISSUE THREAD

**Issue by github-24** [BiliRoamingX/BiliRoamingX#347]
### 原因

占据了屏幕显示空间
![IMG_20240709_074413](https://github.com/BiliRoamingX/BiliRoamingX/assets/31309840/6e4931b1-604d-49fc-a65d-d058e41133a5)

### 功能简述

现在bilibuli新版本搜索结果页太乱了

### 功能逻辑

可以像旧版一样只显示视频吗？

**Comment by Alantemper** [comment]
https://github.com/BiliRoamingX/BiliRoamingX/issues/317#issue-2347336117
