### ISSUE TITLE
版本号伪装

### ISSUE THREAD

**Issue by linanqwq** [BiliRoamingX/BiliRoamingX#352]
### 原因

专栏区域的图文信息，如果版本非最新版，则会显示"[请升级到App最新版本查看图文评论]"

### 功能简述

伪装版本号为最新，同时不影响旧版本功能

### 功能逻辑

在杂项中添加可开关的功能

**Comment by zjns** [comment]
官方bug，即使你是最新版也会这样，应该向官方反馈。
