### ISSUE TITLE
[Feature] 屏蔽首页推荐的充电专属视频

### ISSUE THREAD

**Issue by 123456qwerjpg** [BiliRoamingX/BiliRoamingX#353]
### 原因

首页推荐充电专属视频

### 功能简述

屏蔽首页推荐的充电专属视频

### 功能逻辑

基于过滤推荐内容

**Comment by zjns** [comment]
开启调试模式后刷首页推荐，刷到了充电专属视频后分享日志至此。

**Comment by 123456qwerjpg** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月15日(周一) 晚上6:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BiliRoamingX/BiliRoamingX] [Feature] 屏蔽首页推荐的充电专属视频 (Issue #353)




 
开启调试模式后刷首页推荐，刷到了充电专属视频后分享日志至此。

**Comment by zjns** [comment]
@123456qwerjpg 看不到文件，建议直接来网页上传文件

**Comment by 123456qwerjpg** [comment]
[
[Uploading log_哔哩哔哩(1).zip…]()

**Comment by zjns** [comment]
@123456qwerjpg 没传成功 ![Screenshot_20240717_105956_GitHub.png](https://github.com/user-attachments/assets/ca1ef528-5f4c-4dbf-bd8a-b8479374f748)

**Comment by 123456qwerjpg** [comment]
[log_哔哩哔哩(1).zip](https://github.com/user-attachments/files/16258714/log_.1.zip)

**Comment by zjns** [comment]
已添加，功能入口：首页 > 过滤推荐内容 > 按类型过滤 > 无权查看视频
