### ISSUE TITLE
[Feature] 播放视频时自动全屏但进入详情页不自动播放

### ISSUE THREAD

**Issue by SoulQAQ** [BiliRoamingX/BiliRoamingX#355]
### 原因

B站有这个功能，但它**必须**启用点开视频详情页自动播放才能使用播放自动全屏
这不是我想要的，我只想要开始播放时自动全屏而不想要进入视频详情页时自动播放视频

### 功能简述

启用后
任何地方点进视频详情页不会自动开始播放视频
当开始播放视频时 自动切换到全屏

### 功能逻辑

在设置中添加开关确定功能是否启用

**Comment by zjns** [comment]
全屏之后就只能看到视频画面，不自动播放干啥？
