### ISSUE TITLE
视频播放页面左下角的B站流量卡广告[BUG] 

### ISSUE THREAD

**Issue by milkyummy** [BiliRoamingX/BiliRoamingX#361]
### 系统版本

miui14.0.8

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.3.0

### 问题描述

视频播放页面左下角的B站流量卡广告
![Screenshot_2024-07-18-18-31-27-700_tv danmaku bili](https://github.com/user-attachments/assets/d05a0d14-8d91-4944-972b-1c36c6ed3448)

### 复现步骤

好像，每天点开的第一个视频都有。

### 日志

1

**Comment by zjns** [comment]
已经有了，自己找开关
