### ISSUE TITLE
[Feature] 禁止播放器滑动调节视频亮度

### ISSUE THREAD

**Issue by NetSnorlax** [BiliRoamingX/BiliRoamingX#362]
### 原因

总是误触导致手机亮度异常

### 功能简述

取消官方提供的在播放视频时，在应用内滑动视频区域的调整亮度功能

### 功能逻辑

取消后仍可以从系统层级调整亮度

**Comment by zjns** [comment]
个人没咋误触过，因此不做，而且当前窗口亮度单独调节明显优于系统全局调节
