### ISSUE TITLE
重新添加视频播放页的小窗播放图标

### ISSUE THREAD

**Issue by xinyan-zhou** [BiliRoamingX/BiliRoamingX#363]
### 原因

在新版哔哩哔哩的播放界面上方，小窗播放图标没有了，要在“三个点”里才能找到，非常麻烦，希望您可以让它回归。
![IMG_20240728_200026](https://github.com/user-attachments/assets/9f714ab4-eb16-4e2e-960a-c178b48de5a9)

![IMG_20240728_195954](https://github.com/user-attachments/assets/5f21154a-33b6-4b86-8820-a71c74d0997e)

### 功能简述

让小窗播放图标回归

### 功能逻辑

就像之前的版本那样

**Comment by xinyan-zhou** [comment]
嗯，我已经找到了替代的方案，所以没事了

**Comment by xinyan-zhou** [comment]
嗯

**Comment by xinyan-zhou** [comment]
> ### 原因
> 在新版哔哩哔哩的播放界面上方，小窗播放图标没有了，要在“三个点”里才能找到，非常麻烦，希望您可以让它回归。 ![IMG_20240728_200026](https://private-user-images.githubusercontent.com/176807932/352810325-9f714ab4-eb16-4e2e-960a-c178b48de5a9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNzA2NTYsIm5iZiI6MTcyMjE3MDM1NiwicGF0aCI6Ii8xNzY4MDc5MzIvMzUyODEwMzI1LTlmNzE0YWI0LWViMTYtNGUyZS05NjBhLWMxNzhiNDhkZTVhOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxMjM5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTcxY2RmMmFmYjMxMzEwMTQ2MWQ4NDMzZDI3YjFhZDZjMjMzMWZlOGU4NGIwNzNmYmZmNWM3NjEwYTI4ZWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZZce5MBosxoyq0JyUzr0nscbEhtefyMpP-r6bNyCS5o)
> 
> ![IMG_20240728_195954](https://private-user-images.githubusercontent.com/176807932/352810320-5f21154a-33b6-4b86-8820-a71c74d0997e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNzA2NTYsIm5iZiI6MTcyMjE3MDM1NiwicGF0aCI6Ii8xNzY4MDc5MzIvMzUyODEwMzIwLTVmMjExNTRhLTMzYjYtNGI4Ni04ODIwLWE3MWM3NGQwOTk3ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxMjM5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjE5NWMxYWFjYmM4ZDMxOTg2YzZmMzljYWE3MmFkN2JlMjE0OWZmNTY0M2Y3NzNhZmM3MjE3YTc0OTE4NTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S4sYkuMO9fFEcwieuE7Jo7CXihMv-ljdBtkvkJOAgmk)
> 
> ### 功能简述
> 让小窗播放图标回归
> 
> ### 功能逻辑
> 就像之前的版本那样
> 
> ### 实现参考
> _No response_

**Comment by xinyan-zhou** [comment]
虽然官方有自动进入小窗模式的功能，这看起来可能更方便，但事实上并不是，因为我并不希望退出视频页面 都进入/都不进入 小窗模式，而是看需要进行选择的
![Screenshot_2024-07-28-20-42-25-285_tv danmaku bili](https://github.com/user-attachments/assets/3fa4914f-fe70-4b93-bdba-e7b68756ec9d)

**Comment by zjns** [comment]
> 虽然官方有自动进入小窗模式的功能，这看起来可能更方便，但事实上并不是，因为我并不希望每次退出视频页面 都进入/都不进入 小窗模式，而是看需要进行选择的
> ![Screenshot_2024-07-28-20-42-25-285_tv danmaku bili](https://github.com/user-attachments/assets/3fa4914f-fe70-4b93-bdba-e7b68756ec9d)
> 

下面这个选项也关了就会始终显示了
