### ISSUE TITLE
删除首页顶部直播标签里的“推荐-人气-分区”区域

### ISSUE THREAD

**Issue by mzhhzm** [BiliRoamingX/BiliRoamingX#364]
### 原因

首页顶部的直播标签中，推荐区域的封面图片频繁出现“男性裸露上半身”的内容。尽管我已经多次点击“不感兴趣”，但这一情况仍未得到改善。

### 功能简述

在设置中增加删除首页顶部直播标签里的“推荐-人气-分区”区域的选项

### 功能逻辑

在设置中增加删除首页顶部直播标签里的“推荐-人气-分区”区域的选项

**Comment by zjns** [comment]
> “男性裸露上半身”

？？？

**Comment by mzhhzm** [comment]
![Screenshot_2024-07-29-20-57-03-325_tv danmaku bili-edit](https://github.com/user-attachments/assets/27ee68ba-fd2e-46ee-b012-69d5babd43bb)
类似于这种

**Comment by zjns** [comment]
需求过于私人化，没多大意义，就不弄了
