### ISSUE TITLE
[BUG] 无法分享分享视频

### ISSUE THREAD

**Issue by DensweHero** [BiliRoamingX/BiliRoamingX#366]
### 系统版本

Origin OS 4

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.3.0

### 问题描述

无法分享视频，如分享到QQ群聊是，会提示“非官方应用appid=100951776 (错误码：25201)”。

### 复现步骤

1.随便选一个视频
2.分享
3.选择QQ
4.QQ被拉起后选择分享对象
5.分享错误

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16426803/log_.zip)

**Comment by zjns** [comment]
预期行为，如有需要，可以直接分享链接或者用LSPatch修补QQ后分享。

**Comment by huangsijun17** [comment]
> 预期行为，如有需要，可以直接分享链接或者用LSPatch修补QQ后分享。

哪个模块可以解决这一问题？
QAuxiliary似乎不行。
另外，建议作为已知缺陷在README/文档写明。

**Comment by minortex** [comment]
下载原版安装包，使用SimpleHook对QQ/微信伪装签名。修改安装包后必定会导致签名变化，这是改版apk对常识了。

**Comment by cc1477** [comment]
> > 预期行为，如有需要，可以直接分享链接或者用LSPatch修补QQ后分享。
> 
> 哪个模块可以解决这一问题？ QAuxiliary似乎不行。 另外，建议作为已知缺陷在README/文档写明。

内置[签名助手](https://github.com/xihan123/SignHook)应该可以实现

**Comment by emptylight370** [comment]
> 内置[签名助手](https://github.com/xihan123/SignHook)应该可以实现

我看文档说1.1.13之后都不支持内置模块了？好像还是要自己安装lsp来hook QQ微信，没有root应该做不到？

另外，测试过签名助手必须用对应版本的哔哩安装包来伪装签名才行，现在用8.9.0就必须用8.9.0版本的安装包提取签名。

<details>
<summary>8.9.0官签</summary>
30820257308201c0a00302010202044f3bb0ec300d06092a864886f70d0101050500306f310b300906035504061302434e31123010060355040813094775616e67646f6e67310f300d060355040713065a687568616931133011060355040a130a64616e6d616b752e747631133011060355040b130a64616e6d616b752e74763111300f06035504031308426263616c6c656e3020170d3132303231353133313934305a180f32303636313131383133313934305a306f310b300906035504061302434e31123010060355040813094775616e67646f6e67310f300d060355040713065a687568616931133011060355040a130a64616e6d616b752e747631133011060355040b130a64616e6d616b752e74763111300f06035504031308426263616c6c656e30819f300d06092a864886f70d010101050003818d0030818902818100bfc97a0b763abe924af0bc06a77cfcd42c0352218bdf94c3069ee0046d739acc80f29a63576943d310bdc99fdf92b318b2beb82aa6ed7c1da2b8309b736a3d5a8d453704c5ddb422fcdcf3945b7eec15684e8986ca5be2bced562afeeb64f9922996b5ed58a0783f72e5d6c50db1fb31426ad1f64a555a48543143601f6c1c110203010001300d06092a864886f70d01010505000381810000b766d67b330ebd8d94a67041fc4cdc63337eaae55f6bb27b4afa8f769d6d7020aa12a1044c37849f26e9aaaaba2ee13e1a01c44332428d79832213e18238940ccb95a786fa4c8602e499a8e0068e2d4c8427373a9e0d4b78dbd1f1a5ca410698ccf98ad874684a6fec54778973bc914f44aa7b0e63ede9ce52c0ce99b6207f
</details>

**Comment by 2575757** [comment]
搜一下怎么改B站签名就行了，需要读取B站签名的应用都勾进定义域
