### ISSUE TITLE
保活问题

### ISSUE THREAD

**Issue by NetSnorlax** [BiliRoamingX/BiliRoamingX#372]
### 原因

转到后台一会儿，就要重新加载

### 功能简述

强行保留后台活动

### 功能逻辑

漫游设置里添加强行保活的选择

**Comment by zjns** [comment]
系统问题，国内的定制Android一般都有些设置可以调

**Comment by NetSnorlax** [comment]
> 系统问题，国内的定制Android一般都有些设置可以调

以下三种方法我都尝试过，仍然不行，可以指导一下你所知道的方法吗？
1:从后台页面锁上哔哩哔哩
2:安卓电池优化中选择无限制
3:手机root后尝试从“墓碑”应用中保活，仍然不行
