### ISSUE TITLE
图文历史功能

### ISSUE THREAD

**Issue by NetSnorlax** [BiliRoamingX/BiliRoamingX#373]
### 原因

首页常常推送普通B站用户发的图文，有时候想回顾时却发现没有历史记录，官方提供的仅有专栏的历史记录。

### 功能简述

添加一个图文历史的选项，以供查找图文浏览历史

### 功能逻辑

在历史记录页面的“全部”那一列中添加一个

**Comment by zjns** [comment]
这是我说添加就添加的吗？要有对应的接口才行

**Comment by NetSnorlax** [comment]
> 这是我说添加就添加的吗？要有对应的接口才行

抱歉，我对此并不了解😥
