### ISSUE TITLE
[Feature] 增加老版收藏夹

### ISSUE THREAD

**Issue by fs1314** [BiliRoamingX/BiliRoamingX#380]
### 原因

就是新版收藏夹的UI界面总感觉用起来怪怪的，毕竟最上面多了个“稍后观看”。然后从头也都变成了圆形，感觉增加一个老版收藏夹的UI界面比较好。（不是很理解B站为啥连收藏夹的都要改…）

### 功能简述

就是增加老版的收藏夹的UI界面

### 功能逻辑

就是增加老版的收藏夹的UI界面

### 实现参考

就是增加老版的收藏夹的UI界面
对比图
https://meee.com.tw/4W1sKM3
https://meee.com.tw/0QzqwfZ

**Comment by zjns** [comment]
怀旧旧UI就用老版本

**Comment by fs1314** [comment]
> 怀旧旧UI就用老版本

主要是平时看视频就是用的粉色的app，如果为了收藏特意去打开另一个软件去收藏的话就很麻烦。
而且B站新版本的这个收藏真的是纯粹的负优化。
感觉既然都有“把点按加入默认收藏夹”改成“点按采用老版本收藏”的话，说明大家还是认可老版本的收藏的("▔□▔)

**Comment by zjns** [comment]
> > 怀旧旧UI就用老版本
> 
> 主要是平时看视频就是用的粉色的app，如果为了收藏特意去打开另一个软件去收藏的话就很麻烦。 而且B站新版本的这个收藏真的是纯粹的负优化。 感觉既然都有“把点按加入默认收藏夹”改成“点按采用老版本收藏”的话，说明大家还是认可老版本的收藏的("▔□▔)

难道现在的UI不能收藏？之前的旧UI样式才难看，与时代脱节，迟早淘汰

**Comment by fs1314** [comment]
> > > 怀旧旧UI就用老版本
> > 
> > 
> > 主要是平时看视频就是用的粉色的app，如果为了收藏特意去打开另一个软件去收藏的话就很麻烦。 而且B站新版本的这个收藏真的是纯粹的负优化。 感觉既然都有“把点按加入默认收藏夹”改成“点按采用老版本收藏”的话，说明大家还是认可老版本的收藏的("▔□▔)
> 
> 难道现在的UI不能收藏？之前的旧UI样式才难看，与时代脱节，迟早淘汰

啊这…但是插件的本意不就是如此嘛。
如果说顺应新版本一切的，以前的B站还有左滑调出个人页面，但是直到现在漫游插件也有这个功能。如果说顺应新版本的一切的话，那么左滑这种老功能就完全没有必要了。
比如刚才提到的“点按收藏夹”。就是很多人不想要抖音式的ui界面（就是点按收藏到默认收藏夹），所以才出了插件改回去。
如果是这个功能很难实现的话当我没说。
但是顺应新版本我很难苟同，不是因为我无法适应新版本，新版本的“我的”在右下角等改动我也觉得很好，但是像老版本的楼层也是很好的设计。
设计好不好和老不老版本没啥关系吧？
毕竟是插件也不是B站客户端，本来就可以有很多种功能，而不是自己觉得好就觉得所有人就觉得好叭。
毕竟插件本质上是增加功能，不是把原来的删了然后强行盖新楼…

**Comment by Crystal-RainSlide** [comment]
@fs1314 你可能想看一下这个：https://github.com/BiliRoamingX/BiliRoamingX/issues/263#issuecomment-2120500729
