### ISSUE TITLE
[BUG] 视频详情页简介和评论点击区域过于接近

### ISSUE THREAD

**Issue by lyaurora** [BiliRoamingX/BiliRoamingX#382]
### 系统版本

originos4

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.3.0

### 问题描述

在视频详情页”简介“和”评论“位置过于靠近，右手持握时不容易点击

### 复现步骤

无论是否启动模块里的功能均出现

### 日志

无

### 截图或录屏

原版8.3.0![v8 3 0](https://github.com/user-attachments/assets/294d4c95-088a-4730-808f-7871f5e3b5eb)
打包8.3.0-x1.22.5![v8 3 0-x1 22 5 ](https://github.com/user-attachments/assets/0c3d36d0-95b4-4d9c-a3cb-3dd7b6825027)

**Comment by zjns** [comment]
有意调整的，原来的间距太大了，导致我调大显示大小后都被弹幕输入框遮住了
