### ISSUE TITLE
[改进“报告评论审查结果”功能] 

### ISSUE THREAD

**Issue by Tpyan233** [BiliRoamingX/BiliRoamingX#384]
### 原因

报告评论审查结果的功能即便通过审核也会弹窗提示，我认为这个功能只需要确保我的评论成功发送没有被屏蔽，多加一个成功通过的弹窗反需要用户多进行一次操作，而且与没有通过的弹窗没有区分，需要阅读不短的文本确认是通过还是不通过的弹窗

### 功能简述

我建议可以只弹出没有通过审核的弹窗，如果成功通过审核则不进行弹窗提示

### 功能逻辑

去掉成功通过叔叔审核的弹窗

**Comment by zjns** [comment]
#351 已改进，还没发版
