### ISSUE TITLE
[Feature] 希望增加分区强制屏蔽搜索结果的功能

### ISSUE THREAD

**Issue by dglsjdjdk** [BiliRoamingX/BiliRoamingX#386]
### 原因

1、官方搜索界面已经增加高级搜索，这使得分区屏蔽搜索结果成为可能，
2、我想要这个功能的原因是想将哔哩漫游打造成为我的学术搜索引擎，搜索结果仅仅展示知识、科技、资讯三个分区的内容。这样白天用哔哩漫游学习，晚上用正常哔哩娱乐。十分有助于我的自律。
3、这个功能也可以帮助别人屏蔽他们不想看到的分区的搜索结果如舞蹈区、鬼畜区等等。

### 功能简述

在漫游x设置里可以预设搜索结果显示哪些分区，高级搜索页面不再能修改搜索结果显示哪些分区。   
（这样就可以打造一个完美学术搜索引擎，也可以免去每次要到高级搜索页面调整的麻烦。）

### 功能逻辑

在漫游x设置里可以预设搜索结果显示哪些分区，高级搜索页面不再能修改搜索结果显示哪些分区。
（这样就可以打造一个完美学术搜索引擎，也可以免去每次要到高级搜索页面调整的麻烦。）

### 实现参考

进入搜索页面前提前帮使用者选择好预设的分区，并且使高级搜索面板调整分区功能失效。

**Comment by zjns** [comment]
这只能表明你自律能力还不够

**Comment by dglsjdjdk** [comment]
你说得对，所以我才需要分区屏蔽搜索结果。
