### ISSUE TITLE
图文收藏中将动态和专栏分开

### ISSUE THREAD

**Issue by Helvetica1963** [BiliRoamingX/BiliRoamingX#387]
### 原因

我有收藏美图动态的习惯，收藏的动态数量远多于专栏，但在"我的收藏/图文"一栏中，收藏的动态和专栏是放在一起的，这样子每次找收藏的专栏就不好找

### 功能简述

将"我的收藏/图文"中的动态和专栏区分开，可以分别浏览

### 功能逻辑

点击“我的收藏”后呈现的界面里，将"图文"标签页用"专栏"和"动态"两个标签页取代，或者在"图文"标签页下增加筛选器，用于筛选专栏或动态

**Comment by zjns** [comment]
无法实现
