### ISSUE TITLE
关闭左上角"云视听小电视"水印

### ISSUE THREAD

**Issue by Helvetica1963** [BiliRoamingX/BiliRoamingX#388]
### 原因

有些视频左上角有"云视听小电视"水印，而且观众一方关不掉，影响观感

### 功能简述

增加一个可以关闭"云视听小电视"水印的开关

### 功能逻辑

在播放界面中增加一个可以关闭"云视听小电视"水印的开关

### 实现参考

双指放大视频后，左上角小电视水印在屏幕中的位置是不变的，说明这是一个软水印，并不包含在视频本体中，技术上应该有可能去除

**Comment by zjns** [comment]
已经有了
