### ISSUE TITLE
[Feature] 在视频详情页下划手势展开简介

### ISSUE THREAD

**Issue by sjtt2** [BiliRoamingX/BiliRoamingX#389]
### 原因

展开简介时手部操作不方便，不想移动大拇指到展开按钮

### 功能简述

在视频详情页位于页面最顶部的时候，在任意位置（除去视频播放器位置）下划手势  自动展开简介
![序列 01 00_00_00-00_00_30](https://github.com/user-attachments/assets/9a2f6611-52db-4981-b0ba-4c55c64b536d)

### 功能逻辑

在视频详情页位于页面最顶部的时候，在任意位置（除去视频播放器位置）下划手势  自动展开简介

**Comment by zjns** [comment]
you can you up
