### ISSUE TITLE
[BUG] 替换启动logo功能bug

### ISSUE THREAD

**Issue by T-wilight** [BiliRoamingX/BiliRoamingX#390]
### 系统版本

OriginOS4

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.3.0

### 问题描述

在iQOOneo9spro和红米k40（MIUI14，安卓13）上，这个功能均无法成功替换成相册图片。同时iQOO上在不选择图片时无法隐藏启动logo（在设备内重启是没有logo，但是退出重进还是有），而在k40上是不管怎么设置始终没有logo。

### 复现步骤

1.进入漫游设置-杂项-打开替换启动logo，不选择图片
2.重启后依然有logo出现，设备重启也无济于事

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16588408/log_.zip)

### 截图或录屏

![Screenshot_20240812_224224](https://github.com/user-attachments/assets/b5695d46-5a3e-498c-ae95-3162796752f2)
想直接看见2233娘，logo什么的不要啊

### 补充信息

当前设置的备份，不知道有没有帮助，btw我发现其实我的页中把更多服务去掉，设置也还是能照常出现的，不会像弹窗说的那样
[BiliRoamingX_Pink_backup_20240812224015.zip](https://github.com/user-attachments/files/16588421/BiliRoamingX_Pink_backup_20240812224015.zip)

**Comment by zjns** [comment]
启动logo指底部logo，图片尝试jpg、png等一般格式看看
