### ISSUE TITLE
真侧滑栏

### ISSUE THREAD

**Issue by Lyciuhenl** [BiliRoamingX/BiliRoamingX#391]
### 原因

现在的侧滑栏需要点头像，只是将我的换了个地方，不如不开这个功能直接点右下角的我的

### 功能简述

在主页向右滑直接滑出侧滑栏，类似于QQ主页那样

### 功能逻辑

将直播栏移到右边，最左边的是推荐，这样就不会在向右滑的时候与直播栏冲突

### 实现参考

QQ主页侧滑栏

**Comment by Lyciuhenl** [comment]
我不会编程这些只是想请求这个功能，如果实现不了或者很难，那就算了吧

**Comment by zjns** [comment]
目前这就是个怀旧的摆设，不建议开启，官方也给头像位加了最近功能，就这样吧
