### ISSUE TITLE
[Feature] 部分视频的左下角番剧/游戏推广

### ISSUE THREAD

**Issue by WangYi640** [BiliRoamingX/BiliRoamingX#393]
### 原因

部分视频会出现番剧或游戏的推广(如图)
![Screenshot_20240815_162700](https://github.com/user-attachments/assets/026427aa-0177-401f-8a74-004e6c877bf4)
![Screenshot_20240815_162716](https://github.com/user-attachments/assets/4275dee9-ff98-49d1-abd9-e8239aad5f43)

### 功能简述

屏蔽此类推广

### 功能逻辑

日志
[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16623283/log_.zip)

**Comment by WangYi640** [comment]
补充:
截图1  BV1nz421B7RQ     32秒处
截图2  BV1MW42197aC     12秒处

**Comment by zjns** [comment]
早就有了
