### ISSUE TITLE
[Feature] 屏蔽充电专属视频

### ISSUE THREAD

**Issue by Misaka2298** [BiliRoamingX/BiliRoamingX#398]
### 原因

今日B站上线了“充电专属”视频，必须得开通UP的包年包月充电才可以观看视频。
有些视频甚至是看一半才会变成充电专属，本人已经遇到数次看视频正到最精彩的部分戛然而止提示充电继续观看的情况了。

### 功能简述

在设置里增加“屏蔽充电专属视频”项。

### 功能逻辑

如题，略。

### 实现参考

略。

**Comment by zjns** [comment]
入口呢？首页推荐？动态？
