### ISSUE TITLE
[Feature] 能否添加跳过视频恰饭片段功能

### ISSUE THREAD

**Issue by 2584191127** [BiliRoamingX/BiliRoamingX#401]
### 原因

自动跳过广告，减少手动快进的麻烦

### 功能简述

参考这个仓库https://github.com/HanYaodong/BilibiliSponsorBlock

### 功能逻辑

参考这个仓库https://github.com/HanYaodong/BilibiliSponsorBlock

### 实现参考

https://github.com/HanYaodong/BilibiliSponsorBlock

**Comment by leisurefire** [comment]
基本 API 格式是向 https://www.bsbsb.top/api/skipSegments 地址发送 GET 请求，提供 videoID 和其他相关参数，并返回 JSON：
[{'category': 'sponsor', 'actionType': 'skip', 'segment': [时间戳开始, 时间戳结束], 'UUID':  【UUID，字符串】, 'videoDuration': 【视频持续时间，数字】，, 'locked': 0, 'votes': 0, 'description': ''}]

**Comment by cakexxx** [comment]
你这是铁了心要白嫖喜欢的视频呀[社会社会]

**Comment by cxw620** [comment]
第三方 API 没办法保证稳定性, 有需求可以自己加, 本来就有 clip 也就是番剧跳过片头片尾的功能, 直接把相关结果插入即可.

**Comment by MiKoto-Railgun** [comment]
其实我也是上周才看到这个插件的，很好用挺不错的，要是app端也有这个功能就好了，不过要实现这个功能就只能建服务器了，第三方 API 没办法保证稳定性，作者大概率不会弄，但要是只弄个本地自己选择跳过也好[毕竟有些视频想多看个几遍，跳广告不错]

**Comment by MiKoto-Railgun** [comment]
又或者弄个可识别弹幕跳跳伞空降时间的功能，然后根据这个弹幕时间跳过广告，[最近好多空降弹幕我上周刷还能跳，然后最近就不行了，可是弹幕还在那，不知道是不是我的个例]
