### ISSUE TITLE
[BUG] 闪退

### ISSUE THREAD

**Issue by nanjimenwai** [BiliRoamingX/BiliRoamingX#402]
### 系统版本

ColorOS7

### Android 版本

10

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.3.0

### 问题描述

在发送并上传图片时动态时会发生闪退情况。希望在后续版本更新中对已root用户开放单独xposed模块而不是集成，以提高用户的使用体验。（之前没root时在lspatch发现本模块也为内置形式，但lspatch无法识别，加载器版本为0）

### 复现步骤

1.编辑动态
2.上传图片。
3.继续编排文字
4.闪退

### 日志

已崩溃，无法加载日志。

### 解决办法

希望在后续版本更新中对已root用户开放单独xposed模块而不是集成，以提高用户的使用体验。（之前没root时在lspatch发现本模块也为内置形式，但lspatch无法识别，加载器版本为0），并防止倒卖模块。

**Comment by zjns** [comment]
无日志无法解决问题，另，本模块与 xposed 没有一点关系，之所以 lspatch 能看到是因为共用了 lspatch 签名伪装的能力
