### ISSUE TITLE
[BUG] 卡顿和无响应

### ISSUE THREAD

**Issue by TCOTC** [BiliRoamingX/BiliRoamingX#407]
### 系统版本

ColorOS 13.1

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.10.0

### 问题描述

1. 滑动首页时偶尔卡顿
2. 播放视频时频繁卡顿，长按倍速播放会特别卡（视频每秒只能动几帧）
3. 会出现整个手机都卡得不行的情况
4. 用一阵子之后会反复弹出“哔哩唑哩没有响应”窗口，点击“等待”之后会继续弹出
（此时是可以操作 APP 的，只是卡顿，不是完全动不了）

### 复现步骤

1. 打开 APP
2. 划动首页，划个一两分钟
3. 等到出现一点卡顿再点进一个视频
5. 长按倍速播放

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16709198/log_.zip)

### 截图或录屏

![0109cfdee41c65a02a7c19cb2a57a6e](https://github.com/user-attachments/assets/cfcd3fb8-070c-403f-ad6d-a317fda9e24f)

系统界面也整挂了：

![13068f1e006fd25c21bbe8ac61c04b6](https://github.com/user-attachments/assets/ec4e22a7-6d97-45b9-8d6e-af512ac4e554)

**Comment by zjns** [comment]
新发了一版修复了这个问题，更新试试

**Comment by TCOTC** [comment]
刚刚试着找画面变化大的视频倍速播放看，试了几次，还是会卡成一帧一帧的

**Comment by zjns** [comment]
> 刚刚试着找画面变化大的视频倍速播放看，试了几次，还是会卡成一帧一帧的

更新了吗？1.23.1版本

**Comment by TCOTC** [comment]
刚刚更新的。

无响应好像没有出现了

**Comment by TCOTC** [comment]
等等，你说的更新应该是指下载这个安装吧？

![image](https://github.com/user-attachments/assets/4032d4cd-2d3b-432c-a648-fc01ac8cdb83)

**Comment by zjns** [comment]
> 等等，你说的更新应该是指下载这个安装吗？还是在应用或者群里下载集成包？

当然是应用内推送的或者TG群里的包呀

**Comment by TCOTC** [comment]
哦我搞错了，刚刚在群里下了新的安装包，测试一下没有卡顿了

**Comment by TCOTC** [comment]
不过上个版本的应用内推送下载了安装不了
