### ISSUE TITLE
[BUG] thread-14进程 吃满cpu

### ISSUE THREAD

**Issue by gdd00** [BiliRoamingX/BiliRoamingX#411]
### 系统版本

hyperOS 1.0.18.0

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.10.0

### 问题描述

打开过几秒出现thread-14进程吃满cpu

### 复现步骤

打开app即复现

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16711521/log_.zip)

### 截图或录屏

![Uploading IMG_20240822_214909.jpg…]()

**Comment by zjns** [comment]
已经解决了，更新1.23.1版本
