### ISSUE TITLE
[BUG] 直播间默认原画失效并导致断断续续加载

### ISSUE THREAD

**Issue by AzusaHana** [BiliRoamingX/BiliRoamingX#412]
### 系统版本

ColorOS 14

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.10.0

### 问题描述

打开「直播间默认原画」后，打开直播间一直断续加载，打开花枝选项，仍然是“自动”画质，手动切换原画正常播放
关闭该功能，打开直播间政策播放

### 复现步骤

打开「直播间默认原画」后，打开直播间一直断续加载，打开花枝选项，仍然是“自动”画质，手动切换原画正常播放
关闭该功能，打开直播间政策播放

### 日志

日志内为何含有 access_key？

**Comment by zjns** [comment]
无法复现切无日志
