### ISSUE TITLE
[Feature] 收藏集主题

### ISSUE THREAD

**Issue by Ls-su** [BiliRoamingX/BiliRoamingX#415]
### 原因

喜欢某个收藏集的主题

### 功能简述

可以使用收藏集主题的功能

### 功能逻辑

就像其他非收藏集主题那样，点进去就会有启用主题的窗口那样

### 实现参考

参考使用单个主题的那种

**Comment by zjns** [comment]
请举例一个收藏集主题

**Comment by Ls-su** [comment]
> 请举例一个收藏集主题

Aimer digital collecton-collection 01

**Comment by zjns** [comment]
不像正经的装扮那么全面，不弄了
