### ISSUE TITLE
[Feature] 分p视频的进度被变成了整个以及bv无法再跳转了

### ISSUE THREAD

**Issue by fs1314** [BiliRoamingX/BiliRoamingX#416]
### 原因

1.以前在历史记录中记录的分p视频的进度条是对应单个视频的，比如在哔哩蓝色概念版中就是这样的设计。但是粉色哔哩版本好像变成了整个视频的进度，如图
![Screenshot_20240823_095630(1)](https://github.com/user-attachments/assets/bc674499-febf-4a79-8586-890ceaebb813)
![Screenshot_20240823_085835(1)](https://github.com/user-attachments/assets/4a819424-cd3d-4488-8f5e-61aa5b486e39)
2.以前bv号是可以直接跳转的，但是现在不能跳转了（在蓝色概念版中依然可以跳转，应该是B站把这个功能优化掉了？还是漫游X把这个功能掐了？）
![Screenshot_20240823_085658_edit_2374436058513142(1)](https://github.com/user-attachments/assets/1babc422-13e0-47dc-9f0a-150993dbedbc)
![Screenshot_20240823_085651(1)](https://github.com/user-attachments/assets/fa52481a-ece3-48fe-8303-836abe9d67a1)

### 功能简述

bv号跳转能不能加回来

### 功能逻辑

分p视频的整体进度可以单独输入av号查询，因此我觉得在历史记录中像以前一样记录单个视频的进度就行了

**Comment by fs1314** [comment]
我是最新的漫游x的lspatch

**Comment by zjns** [comment]
进度统计方式变更是官方行为，专栏文章 bv 号不能跳转可能是部分专栏页面换成了原生页面而不是 web 页面导致的，原生页面好像暂时还没有 bv 号跳转功能，当然，也有可能是我强制重定向所有专栏打开为原生页面导致的，其实这篇专栏文章可能默认是 web 页面打开，现在已经取消了这个强制，还没发版，下一版本你再看看

**Comment by fs1314** [comment]
好的谢谢喵












碧翠子
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月23日(周五) 上午10:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BiliRoamingX/BiliRoamingX] [Feature] 分p视频的进度被变成了整个以及bv无法再跳转了 (Issue #416)




 
进度统计方式变更是官方行为，专栏文章 bv 号不能跳转可能是部分专栏页面换成了原生页面而不是 web 页面导致的，原生页面好像暂时还没有 bv 号跳转功能，当然，也有可能是我强制重定向所有专栏打开为原生页面导致的，其实这篇专栏文章可能默认是 web 页面打开，现在已经取消了这个强制，还没发版，下一版本你再看看
