### ISSUE TITLE
[BUG] 重复提示更新

### ISSUE THREAD

**Issue by TCOTC** [BiliRoamingX/BiliRoamingX#421]
### 系统版本

ColorOS 13.1

### Android 版本

13

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.10.0

### 问题描述

安装完最新版之后打开APP，会提示更新

### 复现步骤

1. 打开APP提示有新版本，于是下载安装
2. 安装完成之后打开APP，又弹出一个更新提示

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16737787/log_.zip)

### 截图或录屏

![Screenshot_2024-08-25-03-29-11-61_149003a2d400f6adb210d7e357a3a646](https://github.com/user-attachments/assets/de58da4a-5c8e-4468-b2ee-5faceacf9d5f)

**Comment by hee1310** [comment]
设置应该可以关闭的吧

**Comment by TCOTC** [comment]
不是设置的问题

**Comment by zjns** [comment]
同版本哔哩哔哩不同版本漫游 x 更新时就会这样，忽略即可
