### ISSUE TITLE
[BUG] 长按倍速失效 

### ISSUE THREAD

**Issue by 2584191127** [BiliRoamingX/BiliRoamingX#422]
### 系统版本

hm4.0

### Android 版本

。

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

最新

### 问题描述

将视频切换为2倍速时长按倍速失效
![Screenshot_20240825_102650_tv danmaku bili](https://github.com/user-attachments/assets/1b02a09f-9b91-4e87-a4b9-bd17865f8676)

### 复现步骤

打开一个视频
切换为二倍速
播放一段时间后长按屏幕

### 日志

[log_哔哩哔哩(1).zip](https://github.com/user-attachments/files/16738767/log_.1.zip)

**Comment by zjns** [comment]
无法复现
