### ISSUE TITLE
[Feature] 希望缩减长按倍速文字，关闭长按震动，增加更多字体放大档位或只增加字号。

### ISSUE THREAD

**Issue by douxuebuhui** [BiliRoamingX/BiliRoamingX#423]
### 原因

需要频繁长按倍速，会经常振动手机，引起其他物体振动，引发恼人声响。
合适字号在两个档位之间，比较尴尬。如果能单纯调字体大小，不缩放ui也行。

### 功能简述

感谢大佬做出这么好的插件！已加星！

1、希望缩减长按倍速的提示文字，减少视频遮挡。
如“xxx倍速播放中”改为“3.0x”。（当前设置几倍速，就写几倍速，或者单纯写“倍速”两字也行。）

2、关闭长按倍速的震动。（可以自定义开关最好，要不完全关闭所有震动也行）

3、增加更多字体ui放大档位或只增加字号。
（我的最适合档位在“默认”与“大”之间，太尴尬了。能改成无极进度条或输入放大倍数也行。）

### 功能逻辑

普通交互

**Comment by zjns** [comment]
过于细节化，难得弄

**Comment by douxuebuhui** [comment]
> 过于细节化，难得弄

大佬要不弄下第一第二的也行
