### ISSUE TITLE
[BUG] 自定义倍速选1.2或者1.3两个都回同时亮起，但是这两个不能切换，除了这里都能，且正常

### ISSUE THREAD

**Issue by shixiaoqiangla** [BiliRoamingX/BiliRoamingX#424]
### 系统版本

鸿蒙4.2

### Android 版本

安卓

### 哔哩哔哩版本

HD 版

### 哔哩哔哩版本号

最新

### 问题描述

当输入一些自定义倍速时，选择1.2或者1.3时，不能在这两个倍速中切换，且两个倍速任选一个都会使两个同时亮起，除这两个外其余正常
![Screenshot_20240826_101119_tv danmaku bilibilihd](https://github.com/user-attachments/assets/97380ed5-637e-4bcc-aa75-94843aedccc6)

### 复现步骤

设置一些倍速，包括1.2和1.3，点击任意视频选中这两其中一个

### 日志

[log_哔哩哔哩HD.zip](https://github.com/user-attachments/files/16743259/log_.HD.zip)

### 截图或录屏

![Screenshot_20240826_101119_tv danmaku bilibilihd](https://github.com/user-attachments/assets/5aac2a94-22cc-4a9d-9752-d44a53623ff1)

**Comment by zjns** [comment]
倍速间差值不能小于 0.25
