### ISSUE TITLE
[Feature] 能否添加弹幕字体自定义的功能？

### ISSUE THREAD

**Issue by haoxiaoyueh** [BiliRoamingX/BiliRoamingX#425]
### 原因

我现在使用B站，它默认使用我的系统字体，而不去用它自己的，原本在弹幕设置里的不使用系统推荐字体设置也没有了。所以我觉得不如加入一个可以自定义弹幕字体的功能，这样既可以把B站原字体挂上去，也可以使用自己喜欢的字体来查看弹幕
![image](https://github.com/user-attachments/assets/9485d780-eea5-4fba-991d-f08a839bf2db)

### 功能简述

类似自定义字幕的功能，加入一个自定义弹幕字体的功能

### 功能逻辑

相较于字幕，弹幕所需要的设置可以更少一些，比如B站自己就有调节弹幕大小的功能，那就没必要加在设置里。基本上只需要有一个添加字体的选项和描边大小之类的设置就可以了

### 实现参考

类似自定义字幕![image](https://github.com/user-attachments/assets/14ecdccf-12d7-4972-a81a-da47de05a9a6)

**Comment by zjns** [comment]
没办法很好的区分弹幕和其他浮窗文字内容
