### ISSUE TITLE
[Featu增加搜索屏蔽用户功能吧，求求了

### ISSUE THREAD

**Issue by nevergiveup-111** [BiliRoamingX/BiliRoamingX#426]
### 原因

搜索视频时，总是会出现一些ex的引战视频，广告视频，造谣视频，b站就算拉黑了这个用户还能看到该视频，屏蔽功能只能在首页可以用，能不能去增加一个搜索完视频后，看到哪些不喜欢的视频可以有个选项屏蔽该用户，以至于可以实现以后搜索自己喜欢的内容时，不会再出现这个用户，求求增加一下这个功能吧，每一次搜索都会出现一些令人不适的引战视频，就比如下面这个说什么，黑神话大失所望，就是一个喷黑神话，博得流量的视频，即使我把这个up拉黑了，也会看得到，看到这种引战博流量的视频真的很不适，还有一些推广视频，希望能出一个这种功能优化一下体验，搞得我都不想玩b站了，如果增加了，真的非常感谢😭😭😭😭，
![Screenshot_2024-08-26-16-18-29-832_tv danmaku bili](https://github.com/user-attachments/assets/670098da-742c-4935-b6ca-531a25c07251)

### 功能简述

❶能在搜索完后，加一个，可屏蔽功能，屏蔽用户，屏蔽该视频等等，使你屏蔽后，这个视频会想主页那样的屏蔽功能一样变成不能看这个视频了❷或者说下次搜索，会过滤掉这个up的视频，或者过滤掉一个视频。b站本身的搜索反馈没有用，点了不想看该视频，或者与搜索无关，这个视频还能看得到，真的好恶心
![Uploading Screenshot_2024-08-26-16-26-24-773_tv.danmaku.bili.jpg…]()

### 功能逻辑

像这样，或许还能加一个屏蔽该视频的bv号，让下一次搜索时，关于这个用户的视频不再出现在搜索结果里
![IMG_20240826_162914](https://github.com/user-attachments/assets/11e42dc9-9771-467b-9e3e-7e03d7dd5621)

### 实现参考

❶抖音，都能在搜索时，看到哪个不想看的视频，点击我不喜欢看，都可以过滤掉这个视频，抖音该说的不说，拉黑了真的真的就不会再看到这个用户的视频了。❷b站拉黑了也没用，不加这个功能，真的让人很不适。

**Comment by nevergiveup-111** [comment]
如果增加了，真的非常感谢内置板块的创作者😭😭

**Comment by zjns** [comment]
已经有搜索结果屏蔽的功能了，只是不能像首页推荐那样直接添加
