### ISSUE TITLE
净化直播间浮窗-礼物星球失效

### ISSUE THREAD

**Issue by WuuMark** [BiliRoamingX/BiliRoamingX#428]
### 系统版本

MIUI 10

### Android 版本

8

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.11.0

### 问题描述

净化直播间浮窗-礼物星球开启后会导致直播间加载异常

### 复现步骤

1.打开净化直播间浮窗-礼物星球
2.进入任意直播间
3.提示“加载异常，请重新进入直播间”

### 日志

-

**Comment by zjns** [comment]
无日志
