### ISSUE TITLE
[Feature] 全局记忆画面尺寸

### ISSUE THREAD

**Issue by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [BiliRoamingX/BiliRoamingX#430]
### 原因

相信有很多和我一样使用**全面屏**的用户需要在观看横屏视频时频繁性的手动开启画面**拉伸/填充**的选项，我也知道现在模块的功能列表内有双指缩放手势重定义画面尺寸的功能，但是在很多情况下画面由适应→填充后会牺牲原本画面的许多元素。

### 功能简述

因此在这里做出功能请求，还请作者大大可以让重定义双指缩放手势的功能进行更改，由用户自定义选择**适应/填充**或者**适应/拉伸**。我可以想出来的另一个解决方法是单独列出一个可以全局记忆用户所选择的画面尺寸状态的功能。

### 功能逻辑

请详见功能简述

**Comment by zjns** [comment]
拉伸的画面看起来不怪吗？

**Comment by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [comment]
我觉得还是会有很多用户不想要屏幕黑边并且不介意拉伸的吧，毕竟市面上的手机屏幕分辨率这么多，一直填充以显示总会不得不牺牲很多画面元素，得不偿失
