### ISSUE TITLE
[BUG] 修改默认倍数后，滑动切换竖屏视频，倍速仍然为1倍数

### ISSUE THREAD

**Issue by Sabiary** [BiliRoamingX/BiliRoamingX#432]
### 系统版本

Flyme 11

### Android 版本

14

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

3.19.2

### 问题描述

修改默认倍数后，滑动切换竖屏视频，倍速仍然为1倍数

### 复现步骤

滑动切换竖屏视频，倍速仍然为1倍数

### 日志

[log_bilibili.zip](https://github.com/user-attachments/files/16763012/log_bilibili.zip)

**Comment by zjns** [comment]
修了，目前play版没有发版，国内版发版更新了
