### ISSUE TITLE
[BUG]直播全屏时手机状态栏无法消失且在打开应用时出现黑色页面

### ISSUE THREAD

**Issue by User14303** [BiliRoamingX/BiliRoamingX#439]
### 系统版本

HarmonyOS4.2.0

### Android 版本

13

### 哔哩哔哩版本

HD 版

### 哔哩哔哩版本号

1.46.2

### 问题描述

1.打开应用时会弹出一个带有应用图标的黑色页面，感觉不是很美观，希望移除
2直播间全屏后手机状态栏会持续显示，无法消失，望修复此问题
详情请见视频
### 复现步骤

https://github.com/user-attachments/assets/cf2bb606-6b88-4f26-a306-9a36a9356330

### 日志

视频中已开启调试模式且没有开启哔哩哔哩X中的其它选项，详情请见视

https://github.com/user-attachments/assets/26deb4d1-ee55-484e-b80b-4ff3328e9488

频

**Comment by zjns** [comment]
1. 系统行为 2. 系统兼容性问题
