### ISSUE TITLE
[BUG] 多p播放视频合集列表无法显示

### ISSUE THREAD

**Issue by SanaEcho** [BiliRoamingX/BiliRoamingX#443]
### 系统版本

Flyme10

### Android 版本

安卓13

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

3.18.2

### 问题描述

视频合集列表无法显示

### 复现步骤

打开有合集视频
视频详情页没有合集播放列表
播放器列表按钮只有当前视频

### 日志

[log_bilibili.zip](https://github.com/user-attachments/files/16830610/log_bilibili.zip)

### 截图或录屏

https://github.com/user-attachments/assets/6dba7ec6-9916-428e-8098-3e3bd702e447

**Comment by zjns** [comment]
用新版本
