### ISSUE TITLE
[BUG] hdr画质视频双指缩放失效

### ISSUE THREAD

**Issue by zhyh12** [BiliRoamingX/BiliRoamingX#450]
### 系统版本

coloros14

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.12

### 问题描述

8.12-1995视频hdr画质双指缩放无反应，切换为其他画质后恢复正常。之前没注意，刚试了下8.10就失效了

### 复现步骤

1.打开视频切换hdr画质
2.双指缩放无反应
3.切换为其他画质恢复正常

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16906494/log_.zip)

### 截图或录屏

https://github.com/user-attachments/assets/ae1155ff-fec2-47f8-b810-8aa196d6979d

**Comment by zjns** [comment]
官方原版会有这问题不

**Comment by zhyh12** [comment]
> 官方原版会有这问题不

我不到啊 没会员 抓个有会员的测测？

**Comment by zjns** [comment]
已确认是官方问题，可能是有意限制的
