### ISSUE TITLE
用户空间页屏蔽点赞或投币可能导致无法访问

### ISSUE THREAD

**Issue by HSSkyBoy** [BiliRoamingX/BiliRoamingX#451]
### 系统版本

鸿蒙4.2

### Android 版本

12

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.11.0(8110200)

### 问题描述

屏蔽点赞或投币元素可能在新版本中无法访问个人空间

### 复现步骤

漫游x设置
![Screenshot_20240905_230604](https://github.com/user-attachments/assets/7d1a9fa5-67bd-472f-818d-ed3392972470)

用户空间
![Screenshot_20240905_230611](https://github.com/user-attachments/assets/8fe02d23-6803-4a89-b64b-c0cb1d227e95)

屏蔽点赞或投币
![Screenshot_20240905_230629](https://github.com/user-attachments/assets/2645a04b-8cc0-4f96-a30d-b2d6c1a52707)

打开自己或他人的用户空间(点击头像)

### 日志

[log_哔哩哔哩X.zip](https://github.com/user-attachments/files/16907259/log_.zip)

### 解决办法

删除该元素(不太行)，或在粉版>=8.11.0禁止屏蔽这两个元素

### 补充信息

https://space.bilibili.com/610722152
仅测试粉版，HD版和play版情况未知，但考虑到这两个版本长期未更新，估计没有影响

**Comment by zjns** [comment]
already fixed in https://github.com/BiliRoamingX/BiliRoamingX/commit/d44baa6bcf82b6b9894e85a865beaefda5476d0d.
