### ISSUE TITLE
[BUG] 屏蔽 "充电专属问答回复" 相关动态

### ISSUE THREAD

**Issue by cxw620** [BiliRoamingX/BiliRoamingX#452]
### 系统版本

-

### Android 版本

-

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.10.0

### 问题描述

如图所示：

![Screenshot_20240907_153924_tv danmaku bili_edit_1264197480688864](https://github.com/user-attachments/assets/37ff98d0-9139-49fa-8565-ff10a12f5841)

### 复现步骤

-

### 日志

[log.txt](https://github.com/user-attachments/files/16917020/log.txt)

### 解决办法

现有的 "屏蔽充电专属动态" 没记错的话是检查 DynamicItem.Extend.OnlyFansProperty.has_privilege 字段为 false 即无权查看的充电专属动态。但最近发现充电专属问答的相关动态此字段为 true。

看了眼，其区分于其他动态的特征为 DynamicItem.Extend.dyn_type 字段为 2048。

但是考虑到对于确实发起过充电问答的用户，通过上述特征对动态进行过滤会误伤，没法测试有权限用户的返回内容和无权限用户的返回内容有何差异），因而单列设置 "屏蔽充电专属问答动态" 会更合适？（虽然对于这个UP的88的包月真的有人冲那玩意么）

当然，简单在内容过滤里面把 "充电专属问答" 加上也行。所以需不需要特别加上屏蔽、以何种方式（例如直接按屏蔽充电专属处理，还是单开个选项）留给大佬决断吧。

**Comment by zjns** [comment]
麻烦且无法对比提取特征，目前可以通过关键词或类型（通用 方形）屏蔽，就不动了。
