### ISSUE TITLE
[BUG] 进入视频初期画质模糊

### ISSUE THREAD

**Issue by k2000ghm** [BiliRoamingX/BiliRoamingX#453]
### 系统版本

HyperOS 1.0.45

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.3.0

### 问题描述

在已经有大会员的情况下，进入视频的前10几秒画质会非常模糊，需要等一下才能清晰，猜测为画质模块与大会员冲突

### 复现步骤

打开任意视频
播放

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16917336/log_.zip)

### 解决办法

提供画质模块的开关

**Comment by zjns** [comment]
？不是有自定义默认清晰度功能？

**Comment by k2000ghm** [comment]
> ？不是有自定义默认清晰度功能？

但那个不是半屏的清晰度嘛？我默认是4K，但进入视频的前10几秒不管是全屏还是半屏感觉都是360p的画质，等一小会儿就会变成默认的清晰度

**Comment by k2000ghm** [comment]
> ？不是有自定义默认清晰度功能？

明白了，把半屏清晰度设置成和全屏一致，就可以不用等这10几秒阿，问题关闭
