### ISSUE TITLE
[BUG] B站直播间界面被切割，画面显示不全

### ISSUE THREAD

**Issue by kiniiru8** [BiliRoamingX/BiliRoamingX#458]
### 系统版本

MagicOS 8.0

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.10.0

### 问题描述

直播界面被切割
平板使用粉版（普通版）漫游X，不管是横屏状态下还是竖屏状态下，直播界面均显示不全
![Screenshot_20240911_000817_tv danmaku bili](https://github.com/user-attachments/assets/4cfa01f0-bb46-4545-819e-e62e18778f92)
![Screenshot_20240911_000909_tv danmaku bili](https://github.com/user-attachments/assets/b0ea4d79-7168-4ab0-b6fd-79d78bd73016)

### 复现步骤

1.平板不管横屏还是竖屏状态下，打开哔哩漫游X
2.点击任意直播间
3.发现直播画面被切割

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16947922/log_.zip)

### 截图或录屏

![Screenshot_20240911_000817_tv danmaku bili](https://github.com/user-attachments/assets/8b028e7b-1475-49d5-b996-f3af89861c0f)
![Screenshot_20240911_000909_tv danmaku bili](https://github.com/user-attachments/assets/06f526f2-0053-4061-a74d-66ce21862083)

**Comment by zjns** [comment]
日志无法下载，重新上传下

**Comment by kiniiru8** [comment]
> 日志无法下载，重新上传下

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/16958734/log_.zip)

**Comment by zjns** [comment]
看起来不是模块的问题，方便的话装个原版看看有没有这个问题

**Comment by kiniiru8** [comment]
破案了，确实不是漫游X的问题，平板用B站原版直播画面也是被切割
因为平板应用商店只有哔哩HD，我用手机下的原版分享给平板，使用下来也是同样问题，估计单纯是原版不适配平板
![Screenshot_20240911_144840_tv danmaku bili](https://github.com/user-attachments/assets/dba63679-efdc-4ab4-b17d-1b162c8cd750)
![Screenshot_20240911_144801_tv danmaku bili](https://github.com/user-attachments/assets/d8672411-5dff-4f92-a28d-e7867ca16e6c)
![Screenshot_20240911_144926_tv danmaku bili](https://github.com/user-attachments/assets/4cc5163a-8c1b-47ec-8a35-1fa479bb1a1b)
