### ISSUE TITLE
可以屏蔽发表评论、发表回复功能吗？

### ISSUE THREAD

**Issue by 550-q** [BiliRoamingX/BiliRoamingX#461]
### 原因

不想在任何视频下发表评论，但总有时候控制不住手贱，之前用的手机有root用上帝模式屏蔽评论框，现在用的手机不想root了，所以想问问可不可以把发表评论、回复功能屏蔽了。

### 功能简述

屏蔽视频评论区下面的发评论功能，点击评论回复评论功能，和“消息”页面“回复我的”页面里的“回复”功能。

### 功能逻辑

无

### 实现参考

无

**Comment by zjns** [comment]
无理请求
