### ISSUE TITLE
[Feature] 直播也有评分弹窗了

### ISSUE THREAD

**Issue by zhyh12** [BiliRoamingX/BiliRoamingX#462]
### 原因

直播左下角出现评分弹窗
![Screenshot_2024-09-12-20-47-38-56_149003a2d400f6adb210d7e357a3a646](https://github.com/user-attachments/assets/36f78048-5fda-435b-a47e-2f954737bf8d)

### 功能简述

请求屏蔽

### 功能逻辑

.

### 实现参考

.

**Comment by zjns** [comment]
哪个直播间？

**Comment by zjns** [comment]
低频出现，无法复现，没啥实际影响
