### ISSUE TITLE
[Feature] 直播间分屏状态下可以全屏吗

### ISSUE THREAD

**Issue by zhyh12** [BiliRoamingX/BiliRoamingX#463]
### 原因

看群友讨论旧版直播间有一个优点就是分屏可以看到全部画面，新版分屏只能是以下几种
![Screenshot_2024-09-12-22-51-52-71_2e5e049d2cd102fc8c4a698e5bc18941](https://github.com/user-attachments/assets/0cdd676f-5aa9-42bc-8634-e1103213b99f)
![Screenshot_2024-09-12-22-51-59-95_2e5e049d2cd102fc8c4a698e5bc18941](https://github.com/user-attachments/assets/2e653f1c-4fdb-413a-b593-63e2bf64ccc5)
![Screenshot_2024-09-12-22-52-16-13_2e5e049d2cd102fc8c4a698e5bc18941](https://github.com/user-attachments/assets/c5f77513-f40a-4892-83f5-6cec9134f2a4)
视频已经支持伪装未处于多窗口模式了，直播可不可以

### 功能简述

直播支持伪装未处于多窗口模式

### 功能逻辑

.

### 实现参考

.

**Comment by zjns** [comment]
受控于统一选项
