### ISSUE TITLE
为不适配的设备引入外部播放器

### ISSUE THREAD

**Issue by shoufu233** [BiliRoamingX/BiliRoamingX#464]
### 原因

像pixel全系或者xperia这种手机，b站没有支持，2k和4k屏只能看1080p，码率还低。但其实谷歌的tensor和Sony的骁龙都没有编解码问题，我用mx是可以smb串流硬解4k50m码率的，谷歌如果强开b站4k会卡（表现为一直缓存），sony不会。

### 功能简述

取b站的视频URL，配合potplayer或者mx这类的支持串流的播放器，兴许可以调用系统解码器播放，这样就解决了适配问题，mx估计还比b站省电不少

### 功能逻辑

在设置中添加使用外部播放器的选项。点开视频后拉起播放器播放，像smb

### 实现参考

smb类似物，拜托了谷歌用户已经看了9代1080p了😭

**Comment by zjns** [comment]
不应该向B站官方反馈这个问题吗
