### ISSUE TITLE
去掉使用流量的提示

### ISSUE THREAD

**Issue by twcgzgs** [BiliRoamingX/BiliRoamingX#466]
### 原因

我卡流量比较多，一般直接用流量刷b站。然后它总有那个使用流量的提示，能把它去掉吗

### 功能简述

就去掉那个使用流量刷b站的提示

### 功能逻辑

就在那个播放器那里弄个选项呗，是否关闭使用移动数据提示

### 实现参考

不知道

**Comment by zjns** [comment]
移除视频浮窗
