### ISSUE TITLE
[Feature] 添加 “弹幕使用推荐字体”设置项

### ISSUE THREAD

**Issue by WangYi640** [BiliRoamingX/BiliRoamingX#467]
### 原因

在8.10左右版本，粉版移除了弹幕字体跟随系统字体开关
系统字体相对于“推荐字体”更粗更圆，描边更细。易于阅读。

### 功能简述

![Screenshot_20240913_223157](https://github.com/user-attachments/assets/85879c8a-2c89-44d1-a276-8d17aecf703d)
![Screenshot_20240913_223227](https://github.com/user-attachments/assets/fbe6684f-dacc-46cf-a5c8-37d1bfaf8c89)

### 功能逻辑

在漫游设置里面 添加使用系统推荐字体 开关

### 实现参考

本人实测
1.清除数据重新安装新版b站 默认使用推荐字体
2.安装旧版b站－关闭推荐字体－覆盖安装新版b站。设置项里 使用推荐字体开关 消失，但是弹幕仍然跟随系统字体

猜测：官方只是隐藏了设置项入口

**Comment by zjns** [comment]
试试看禁止下载基础库

**Comment by WangYi640** [comment]
> 试试看禁止下载基础库

无效 该更新不属于热更新
应该是在8.3~8.10之间的某个版本重写了弹幕设置界面 导致功能缺失（砍掉）
