### ISSUE TITLE
[BUG] 首页推荐刷新出错，按类型过滤失效

### ISSUE THREAD

**Issue by yongrenx** [BiliRoamingX/BiliRoamingX#469]
### 系统版本

HyperOS 1.0.13.0.UMCCNXM

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.10.0

### 问题描述

打开app刷新首页就会出错，之后也无法刷新，只能重启app，按类型过滤取消勾选也无法恢复

### 复现步骤

打开app刷新首页就会出错，之后也无法刷新，只能重启app

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/17000734/log_.zip)
配置文件
[BiliRoamingX_Pink_backup_20240914104453.zip](https://github.com/user-attachments/files/17000744/BiliRoamingX_Pink_backup_20240914104453.zip)

### 截图或录屏

![Screenshot_2024-09-14-11-11-07-582_tv danmaku bili](https://github.com/user-attachments/assets/92f17cc0-ebcb-4d4b-8472-f2bba14a671c)

**Comment by zjns** [comment]
检查你的首页过滤设置

**Comment by yongrenx** [comment]
首页过滤指定时长的视频，就会出现这个bug，我自己试60s以下这个bug就经常出现，必须重启app

**Comment by yongrenx** [comment]
不太容易控制变量，反正我这样设置触发bug的频率很高
![Screenshot_2024-09-14-13-23-41-339_tv danmaku bili](https://github.com/user-attachments/assets/47879e2a-8b6f-439b-b59f-34c07098bc1d)
![Screenshot_2024-09-14-13-24-17-307_tv danmaku bili](https://github.com/user-attachments/assets/22e8c8a2-4c08-4f5c-b57f-9c7591ea3066)

**Comment by cavendish-123** [comment]
相同问题
按关键词过滤保持默认不出问题
