### ISSUE TITLE
[Feature] 添加视频标题关键词屏蔽和简化功能

### ISSUE THREAD

**Issue by douxuebuhui** [BiliRoamingX/BiliRoamingX#470]
### 原因

教学类视频，标题往往写的很长，比如哪本书哪个知识点
标题太长，特别是合集，标题无法看全

### 功能简述

将长标题用自定义设置的方式缩减，
比如：“大不列颠及北爱尔兰联合王国”
自定义成，“英国”
实现缩减标题长度

### 功能逻辑

。

**Comment by zjns** [comment]
视频信息自由复制可以查看完整标题名

**Comment by douxuebuhui** [comment]
> 视频信息自由复制可以查看完整标题名

但是合集视频有很多，点击“选集”，一个一个复制查看太不方便了
