### ISSUE TITLE
[Feature]视频详情页点击评论区图片或者进入下方其他推荐视频页时，原视频可以不暂停

### ISSUE THREAD

**Issue by soeyu** [BiliRoamingX/BiliRoamingX#473]
### 原因

场景1：查看图片内容；
场景2：查看其他稿件的非视频内容（如评论、up主空间其他信息）期间；
可以保持原播放中的视频不暂停，提高播放连贯性

### 功能简述

点击进入视频下方其他内容时，播放中的视频仍能保持播放。

### 功能逻辑

设置开关打开后
视频详情页点击评论区图片放大、点击推荐视频、进入up主空间，播放中的视频不暂停

### 实现参考

在6.x版本前是使用这个不暂停的逻辑，后续更新改掉了

**Comment by zjns** [comment]
8.14.0官方又改回来了

**Comment by soeyu** [comment]
作者大大@zjns，根据粉版 8.9.0(8090300) with 漫游X 1.24.0的更新说明，如果后续都停留在8.9，是否可以尝试在该版本实现这个功能？😂
