### ISSUE TITLE
[BUG] 自行打包HD版时出现错误

### ISSUE THREAD

**Issue by susulqx** [BiliRoamingX/BiliRoamingX#475]
### 系统版本

原版java11

### Android 版本

Windows11

### 哔哩哔哩版本

HD 版

### 哔哩哔哩版本号

1.46.2

### 问题描述

自行打包HD版时出现错误，原版java11，HD版本：1.46.2
我也打包过粉、play版，都没有出现错误

### 复现步骤

无

### 日志

java -jar revanced-cli.jar patch --merge integrations.apk --patch-bundle patches.jar  --signing-levels 1,2,3 bilibili.apk
淇℃伅: Loading patches
淇℃伅: Decoding app manifest
淇℃伅: Export all activities excluded
淇℃伅: Predictive back gesture excluded
淇℃伅: Enable Android debugging excluded
淇℃伅: Change package name excluded
淇℃伅: Spoof SIM country excluded
淇℃伅: Setting patch options
淇℃伅: Merging integrations
淇℃伅: Deleting existing temporary files directory
淇℃伅: Decoding resources
淇℃伅: Executing patches
淇℃伅: Anti RecyclerView obfuscation succeeded
淇℃伅: App icon succeeded
淇℃伅: Append signature info for LSPatch succeeded
淇℃伅: Auto like succeeded
淇℃伅: BL route intercept succeeded
淇℃伅: BLog succeeded
淇℃伅: Bili adjust layout (codes) succeeded
淇℃伅: Bili adjust layout (resources) succeeded
淇℃伅: Bili library patch succeeded
淇℃伅: BiliRoamingX settings entrance succeeded
淇℃伅: Blkv succeeded
淇℃伅: Block thai comment succeeded
淇℃伅: Block up recommend ads succeeded
淇℃伅: Brotli succeeded
淇℃伅: Cache redirect succeeded
淇℃伅: Channel model fix succeeded
淇℃伅: Comment word search url succeeded
淇℃伅: Config succeeded
淇℃伅: Config integration succeeded
淇℃伅: Copy enhance succeeded
淇℃伅: Crash handler succeeded
淇℃伅: Custom splash succeeded
淇℃伅: Custom theme color succeeded
淇℃伅: Dark switch succeeded
淇℃伅: Default playback speed succeeded
淇℃伅: Disable auto select succeeded
淇℃伅: Disable live room double click succeeded
淇℃伅: Dpi succeeded
淇℃伅: Drawer succeeded
淇℃伅: Enable Key mapping succeeded
淇℃伅: Fake not in multi window mode succeeded
淇℃伅: Fix app setting preference layout succeeded
淇℃伅: Fix preference click succeeded
淇℃伅: Fix preference manager succeeded
淇℃伅: Forbid auto subscribe succeeded
淇℃伅: Forbid live room auto float succeeded
淇℃伅: Forbid switch live room succeeded
淇℃伅: Force hardware codec succeeded
淇℃伅: Hd preference fragment succeeded
淇℃伅: Hide follow button succeeded
淇℃伅: Inject DocumentsProvider succeeded
淇℃伅: Inject more scheme succeeded
淇℃伅: Integrations succeeded
淇℃伅: Json succeeded
淇℃伅: Keep data when uninstall succeeded
淇℃伅: Lib bili succeeded
淇℃伅: Long press playback speed succeeded
淇℃伅: Main activity patch succeeded
淇℃伅: Make text selectable succeeded
淇℃伅: Modify modifier succeeded
淇℃伅: Moss succeeded
淇℃伅: Music notification succeeded
淇℃伅: Number format succeeded
淇℃伅: OkHttp succeeded
淇℃伅: Override certificate pinning succeeded
淇℃伅: Override playback speed succeeded
淇℃伅: Pegasus hook succeeded
淇℃伅: Per app language succeeded
淇℃伅: Play url succeeded
淇℃伅: Player core succeeded
淇℃伅: Player gesture detector hook succeeded
淇℃伅: Player toast succeeded
淇℃伅: ProtoBuf print succeeded
淇℃伅: Remember playback speed succeeded
淇℃伅: Remove managerSpaceActivity succeeded
淇℃伅: Save comment images succeeded
淇℃伅: Search type succeeded
淇℃伅: Share succeeded
淇℃伅: Splash succeeded
淇℃伅: Subtitle import and save succeeded
淇℃伅: Subtitle import and save button succeeded
淇℃伅: Subtitle style succeeded
淇℃伅: Teenager mode succeeded
淇℃伅: Text fold succeeded
淇℃伅: Toast succeeded
淇℃伅: Trial quality succeeded
淇℃伅: Uid copy no prefix succeeded
淇℃伅: Unlock ProtoBuf succeeded
淇℃伅: Upgrade succeeded
淇℃伅: Video default quality succeeded
淇℃伅: Webview succeeded
淇℃伅: Compiling patched dex files
淇℃伅: Compiled classes.dex
淇℃伅: Compiled classes2.dex
淇℃伅: Compiled classes3.dex
淇℃伅: Compiled classes4.dex
淇℃伅: Compiled classes5.dex
淇℃伅: Compiled classes6.dex
淇℃伅: Compiled classes7.dex
淇℃伅: Compiled classes8.dex
淇℃伅: Compiled classes9.dex
淇℃伅: Compiled classes10.dex
淇℃伅: Compiled classes11.dex
淇℃伅: Compiled classes12.dex
淇℃伅: Compiled classes13.dex
淇℃伅: Compiled classes14.dex
淇℃伅: Compiled classes15.dex
淇℃伅: Compiled classes16.dex
淇℃伅: Compiled classes17.dex
淇℃伅: Compiled classes18.dex
淇℃伅: Compiled classes19.dex
淇℃伅: Compiled classes20.dex
淇℃伅: Compiled classes21.dex
淇℃伅: Compiled classes22.dex
淇℃伅: Compiled classes23.dex
淇℃伅: Compiled classes24.dex
淇℃伅: Compiled classes25.dex
淇℃伅: Compiling modified resources
淇℃伅: Aligning APK
org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1174)
        at app.revanced.library.ApkSigner.newKeyStore(ApkSigner.kt:56)
        at app.revanced.library.ApkUtils.newPrivateKeyCertificatePair(ApkUtils.kt:114)
        at app.revanced.library.ApkUtils.signApk(ApkUtils.kt:168)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:331)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)
        ... 15 more

**Comment by zjns** [comment]
jdk 版本问题
