### ISSUE TITLE
[BUG] 把显示调成小之后，视频里的防遮挡就会偏移

### ISSUE THREAD

**Issue by sg843** [BiliRoamingX/BiliRoamingX#480]
### 系统版本

miui12.5，miui13，澎湃os，测试过很多手机

### Android 版本

11，12，14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

最新版8.1.0有这个问题，除了最新版，7.7.8，7.8.0，8.3.0都测过，都是这样

### 问题描述

在哔哩漫游里面，把显示调成小之后，视频里的防遮挡就会偏移

### 复现步骤

把显示调整小，然后去找一个有防遮挡的视频，防遮挡偏移

### 日志

[Uploading info.json…]()

### 截图或录屏

![Screenshot_2024-09-18-14-03-49-208_tv danmaku bili](https://github.com/user-attachments/assets/8cbde79b-6fb3-4d7c-985e-ebf6b9ca29cb)

### 解决办法

我也不知道

### 补充信息

在哔哩漫游里面，把显示调成小之后，去看这个视频BV1cP4y1373s

**Comment by zjns** [comment]
为了使CC字幕和弹幕在更改显示大小后字体大小不变特殊处理的（会朝着相反的方向变化），这个副作用之前一直没发现，可能没办法解决，要做取舍。
