### ISSUE TITLE
视频标题取消加粗

### ISSUE THREAD

**Issue by alexchend** [BiliRoamingX/BiliRoamingX#483]
### 原因

![Screenshot_2024-09-20-23-50-41-537_tv danmaku bili-edit](https://github.com/user-attachments/assets/79e06247-f5ec-4451-9ffc-b817e7d0f43c)
更新以后发现视频标题文字变粗了

### 功能简述

希望能取消这个加粗效果

### 功能逻辑

加一个开关

### 实现参考

谢谢谢谢

**Comment by zjns** [comment]
没必要，自适应
