### ISSUE TITLE
[Feature] 绕过账号实名信息观看直播间

### ISSUE THREAD

**Issue by shenfluke** [BiliRoamingX/BiliRoamingX#485]
### 原因

Edit: (回复楼下@zjns) 我是海外华人，用的海外手机号不需要实名就能注册B站。鉴于这功能对极少用户适用，就提一嘴，能实现的话当然更好。

部分游戏直播间(APEX, CSGO等分区)需要账号实名认证才能观看。一进直播间就跳出以下弹窗，直播间黑屏，按下“我知道了”就会退出直播间。
![WhatsApp Image 2024-09-21 at 16 40 02_6e882ad0](https://github.com/user-attachments/assets/797fedb4-053b-4110-92a6-4859f7ca4b98)

### 功能简述

在账号没有实名认证的状态下观看直播间

### 功能逻辑

屏蔽实名认证提示弹窗，绕过账号实名信息观看直播间

### 实现参考
Edit: 日志
[log_哔哩哔哩.zip](https://github.com/user-attachments/files/17083562/log_.zip)

**Comment by zjns** [comment]
不是手机号注册的账号？

**Comment by zjns** [comment]
如果是一进直播间就有这个弹窗，你可以开启调试模式复现然后把日志贴到这
