### ISSUE TITLE
[Feature] 希望能修复播放器切换成旧版后，稍后再看页出现的问题

### ISSUE THREAD

**Issue by Dome-World** [BiliRoamingX/BiliRoamingX#486]
### 原因

播放器在设置中切换成旧版后与现在新版的稍后再看页不匹配，无论选什么播放都是第一个视频

### 功能简述

这是哔哩哔哩自身的问题，只是想问问这个问题还会修吗

### 功能逻辑

和新版播放器一样最好了

**Comment by zjns** [comment]
新版上旧版播放器问题越来越多，没有这个必要，迟早有一天要被完全移除
