### ISSUE TITLE
[BUG] 小程序转连接功能失效

### ISSUE THREAD

**Issue by mugongzi520** [BiliRoamingX/BiliRoamingX#488]
### 系统版本

redimeui 5.0

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.40.0

### 问题描述

小程序转连接分享功能失效

### 复现步骤

打开小程序转连接分享功能 分享视频发现依然是分享小程序 并且因为签名无法分享

### 日志

[log_哔哩哔哩.zip](https://github.com/user-attachments/files/17089222/log_.zip)

**Comment by zjns** [comment]
不支持这么老的版本
