### ISSUE TITLE
[BUG] “需要时才下载基础组件库”没有效果

### ISSUE THREAD

**Issue by stevenlele** [BiliRoamingX/BiliRoamingX#489]
### 系统版本

Android 14

### Android 版本

Android 14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.14.0

### 问题描述

实际 app 还是会下载无用组件，占用不少空间。

不知道取消原本的“禁止下载组件库”是出于什么考量，是否可以加回来？

### 复现步骤

在存储空间管理中清除基础组件库数据，然后重启 app。发现 app 还是自动下载了 200 多 MB 的组件库。查看后发现其中 `uper` 和 `mall` 占用的空间最多，但是实际都用不上。（已隐藏发布和会员购底部标签，打开 app 也并未主动触发创作/会员购相关功能）

### 日志

[log.txt](https://github.com/user-attachments/files/17091830/log.txt)（唯一一条含有 `modPreloadRes` 的记录）

### 解决办法

如果可能，恢复原本的“禁止下载组件库”功能。

**Comment by zjns** [comment]
效果是有的，从1个多G降到200M左右了，虽然占用多了点，但不影响有需要更多功能的用户，不会出现有些功能无法使用的情况
