### ISSUE TITLE
[Feature] 有没有可能把动态搜索修复

### ISSUE THREAD

**Issue by zhyh12** [BiliRoamingX/BiliRoamingX#490]
### 原因

去年B站把所有版本的动态全站搜索的功能都下线了，一些老版本比如6.12还保留动态搜索框但是搜索不到东西
![IMG_20240921_082558](https://github.com/user-attachments/assets/dd340862-704a-4f08-bc3e-926e5dc4284d)
![IMG_20240921_082615](https://github.com/user-attachments/assets/c883b99d-3554-45b9-aac4-b03a9663531d)

### 功能简述

这个功能能否修复，或者在搜索栏加一个动态搜索tag

### 功能逻辑

.

### 实现参考

.

**Comment by zjns** [comment]
接口已经下了
